package kr.re.kribb.mapper;

import kr.re.kribb.model.GeneInfo;
import kr.re.kribb.model.GeneInfoExample;

public interface GeneInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GeneInfo
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	int countByExample(GeneInfoExample example);

	GeneInfo getGeneInfo(String genes);
}