package kr.re.kribb.mapper;

import java.util.ArrayList;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import kr.re.kribb.model.InDel_Marker;
import kr.re.kribb.model.InDel_MarkerExample;
import kr.re.kribb.model.Marker;
import kr.re.kribb.model.SnpMarker;
import kr.re.kribb.model.TmVO;

public interface InDel_MarkerMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table InDel_Marker
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	int countByExample(InDel_MarkerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table InDel_Marker
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	InDel_Marker selectByPrimaryKey(Integer id);

	int chrCountInDel(String chrom);

	ArrayList<Marker> getChrMarkers(TmVO chrMarkerVO);

	int getCountPos(@Param("chrom") String chrom, @Param("pos") int pos,
			@Param("endPos") int endPos);
}