package kr.re.kribb.mapper;

import java.util.ArrayList;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import kr.re.kribb.model.Marker;
import kr.re.kribb.model.SnpMarker;
import kr.re.kribb.model.SnpMarkerExample;
import kr.re.kribb.model.SnpMarkerSearch;
import kr.re.kribb.model.TmVO;

public interface SnpMarkerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SNP_Marker
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	int countByExample(SnpMarkerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SNP_Marker
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	Marker selectByPrimaryKey(Integer id);

	ArrayList<SnpMarker> getMarkers(SnpMarkerSearch search);

	int countMarkers(SnpMarkerSearch search);

	ArrayList<SnpMarker> traitSelect(@Param("equalsA") List<String> equalsA,
			@Param("equalsB") List<String> equalsB);

	ArrayList<SnpMarker> traitSelect(TmVO tmVO);

	int chrCountSNP(String chrom);

	ArrayList<Marker> getChrMarkers(TmVO chrMarkerVO);

	int getCountPos(@Param("chrom") String chrom, @Param("pos") int pos,
			@Param("endPos") int endPos);
	
}