package kr.re.kribb.mapper;

import java.util.ArrayList;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import kr.re.kribb.model.Marker;
import kr.re.kribb.model.SSR_Marker;
import kr.re.kribb.model.SSR_MarkerExample;
import kr.re.kribb.model.SnpMarker;
import kr.re.kribb.model.TmVO;

public interface SSR_MarkerMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SSR_Marker
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	int countByExample(SSR_MarkerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SSR_Marker
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	SSR_Marker selectByPrimaryKey(Integer id);

	int chrCountSSR(String chrom);

	ArrayList<Marker> getChrMarkers(TmVO chrMarkerVO);

	int getCountPos(@Param("chrom") String chrom, @Param("pos") int pos,
			@Param("endPos") int endPos);

	SSR_Marker getSsrMarker(SSR_Marker ssrVO);
}