package kr.re.kribb.mapper;

import java.util.ArrayList;

import kr.re.kribb.model.Trait;
import kr.re.kribb.model.TraitExample;

public interface TraitMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trait
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	int countByExample(TraitExample example);
	
	ArrayList<Trait> selectTraits();
	
}