package kr.re.kribb.model;

import java.util.ArrayList;
import java.util.List;

public class ChromosomeInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ChromosomeInfo
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ChromosomeInfo
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ChromosomeInfo
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ChromosomeInfo
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	protected int limitStart = -1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ChromosomeInfo
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	protected int limitMaxSize = -1;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ChromosomeInfo
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public ChromosomeInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ChromosomeInfo
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ChromosomeInfo
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ChromosomeInfo
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ChromosomeInfo
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ChromosomeInfo
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ChromosomeInfo
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ChromosomeInfo
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ChromosomeInfo
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ChromosomeInfo
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ChromosomeInfo
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ChromosomeInfo
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setLimitStart(int limitStart) {
		this.limitStart = limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ChromosomeInfo
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public int getLimitStart() {
		return limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ChromosomeInfo
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setLimitMaxSize(int limitMaxSize) {
		this.limitMaxSize = limitMaxSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ChromosomeInfo
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public int getLimitMaxSize() {
		return limitMaxSize;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ChromosomeInfo
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andChrnoIsNull() {
			addCriterion("ChrNo is null");
			return (Criteria) this;
		}

		public Criteria andChrnoIsNotNull() {
			addCriterion("ChrNo is not null");
			return (Criteria) this;
		}

		public Criteria andChrnoEqualTo(String value) {
			addCriterion("ChrNo =", value, "chrno");
			return (Criteria) this;
		}

		public Criteria andChrnoNotEqualTo(String value) {
			addCriterion("ChrNo <>", value, "chrno");
			return (Criteria) this;
		}

		public Criteria andChrnoGreaterThan(String value) {
			addCriterion("ChrNo >", value, "chrno");
			return (Criteria) this;
		}

		public Criteria andChrnoGreaterThanOrEqualTo(String value) {
			addCriterion("ChrNo >=", value, "chrno");
			return (Criteria) this;
		}

		public Criteria andChrnoLessThan(String value) {
			addCriterion("ChrNo <", value, "chrno");
			return (Criteria) this;
		}

		public Criteria andChrnoLessThanOrEqualTo(String value) {
			addCriterion("ChrNo <=", value, "chrno");
			return (Criteria) this;
		}

		public Criteria andChrnoLike(String value) {
			addCriterion("ChrNo like", value, "chrno");
			return (Criteria) this;
		}

		public Criteria andChrnoNotLike(String value) {
			addCriterion("ChrNo not like", value, "chrno");
			return (Criteria) this;
		}

		public Criteria andChrnoIn(List<String> values) {
			addCriterion("ChrNo in", values, "chrno");
			return (Criteria) this;
		}

		public Criteria andChrnoNotIn(List<String> values) {
			addCriterion("ChrNo not in", values, "chrno");
			return (Criteria) this;
		}

		public Criteria andChrnoBetween(String value1, String value2) {
			addCriterion("ChrNo between", value1, value2, "chrno");
			return (Criteria) this;
		}

		public Criteria andChrnoNotBetween(String value1, String value2) {
			addCriterion("ChrNo not between", value1, value2, "chrno");
			return (Criteria) this;
		}

		public Criteria andChrlenIsNull() {
			addCriterion("ChrLen is null");
			return (Criteria) this;
		}

		public Criteria andChrlenIsNotNull() {
			addCriterion("ChrLen is not null");
			return (Criteria) this;
		}

		public Criteria andChrlenEqualTo(Integer value) {
			addCriterion("ChrLen =", value, "chrlen");
			return (Criteria) this;
		}

		public Criteria andChrlenNotEqualTo(Integer value) {
			addCriterion("ChrLen <>", value, "chrlen");
			return (Criteria) this;
		}

		public Criteria andChrlenGreaterThan(Integer value) {
			addCriterion("ChrLen >", value, "chrlen");
			return (Criteria) this;
		}

		public Criteria andChrlenGreaterThanOrEqualTo(Integer value) {
			addCriterion("ChrLen >=", value, "chrlen");
			return (Criteria) this;
		}

		public Criteria andChrlenLessThan(Integer value) {
			addCriterion("ChrLen <", value, "chrlen");
			return (Criteria) this;
		}

		public Criteria andChrlenLessThanOrEqualTo(Integer value) {
			addCriterion("ChrLen <=", value, "chrlen");
			return (Criteria) this;
		}

		public Criteria andChrlenIn(List<Integer> values) {
			addCriterion("ChrLen in", values, "chrlen");
			return (Criteria) this;
		}

		public Criteria andChrlenNotIn(List<Integer> values) {
			addCriterion("ChrLen not in", values, "chrlen");
			return (Criteria) this;
		}

		public Criteria andChrlenBetween(Integer value1, Integer value2) {
			addCriterion("ChrLen between", value1, value2, "chrlen");
			return (Criteria) this;
		}

		public Criteria andChrlenNotBetween(Integer value1, Integer value2) {
			addCriterion("ChrLen not between", value1, value2, "chrlen");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ChromosomeInfo
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ChromosomeInfo
     *
     * @mbggenerated do_not_delete_during_merge Tue Jul 29 20:42:28 KST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}