package kr.re.kribb.model;

public class ChromosomeInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ChromosomeInfo.ChrNo
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String chrno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ChromosomeInfo.ChrLen
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private Integer chrlen;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ChromosomeInfo.ChrNo
	 * @return  the value of ChromosomeInfo.ChrNo
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getChrno() {
		return chrno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ChromosomeInfo.ChrNo
	 * @param chrno  the value for ChromosomeInfo.ChrNo
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setChrno(String chrno) {
		this.chrno = chrno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ChromosomeInfo.ChrLen
	 * @return  the value of ChromosomeInfo.ChrLen
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public Integer getChrlen() {
		return chrlen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ChromosomeInfo.ChrLen
	 * @param chrlen  the value for ChromosomeInfo.ChrLen
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setChrlen(Integer chrlen) {
		this.chrlen = chrlen;
	}
}