package kr.re.kribb.model;

import java.util.ArrayList;
import java.util.List;

public class GeneticMapExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table geneticMap
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table geneticMap
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table geneticMap
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table geneticMap
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	protected int limitStart = -1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table geneticMap
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	protected int limitMaxSize = -1;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table geneticMap
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public GeneticMapExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table geneticMap
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table geneticMap
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table geneticMap
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table geneticMap
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table geneticMap
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table geneticMap
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table geneticMap
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table geneticMap
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table geneticMap
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table geneticMap
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table geneticMap
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setLimitStart(int limitStart) {
		this.limitStart = limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table geneticMap
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public int getLimitStart() {
		return limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table geneticMap
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setLimitMaxSize(int limitMaxSize) {
		this.limitMaxSize = limitMaxSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table geneticMap
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public int getLimitMaxSize() {
		return limitMaxSize;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table geneticMap
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdxIsNull() {
			addCriterion("idx is null");
			return (Criteria) this;
		}

		public Criteria andIdxIsNotNull() {
			addCriterion("idx is not null");
			return (Criteria) this;
		}

		public Criteria andIdxEqualTo(Integer value) {
			addCriterion("idx =", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxNotEqualTo(Integer value) {
			addCriterion("idx <>", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxGreaterThan(Integer value) {
			addCriterion("idx >", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxGreaterThanOrEqualTo(Integer value) {
			addCriterion("idx >=", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxLessThan(Integer value) {
			addCriterion("idx <", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxLessThanOrEqualTo(Integer value) {
			addCriterion("idx <=", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxIn(List<Integer> values) {
			addCriterion("idx in", values, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxNotIn(List<Integer> values) {
			addCriterion("idx not in", values, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxBetween(Integer value1, Integer value2) {
			addCriterion("idx between", value1, value2, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxNotBetween(Integer value1, Integer value2) {
			addCriterion("idx not between", value1, value2, "idx");
			return (Criteria) this;
		}

		public Criteria andChromIsNull() {
			addCriterion("chrom is null");
			return (Criteria) this;
		}

		public Criteria andChromIsNotNull() {
			addCriterion("chrom is not null");
			return (Criteria) this;
		}

		public Criteria andChromEqualTo(String value) {
			addCriterion("chrom =", value, "chrom");
			return (Criteria) this;
		}

		public Criteria andChromNotEqualTo(String value) {
			addCriterion("chrom <>", value, "chrom");
			return (Criteria) this;
		}

		public Criteria andChromGreaterThan(String value) {
			addCriterion("chrom >", value, "chrom");
			return (Criteria) this;
		}

		public Criteria andChromGreaterThanOrEqualTo(String value) {
			addCriterion("chrom >=", value, "chrom");
			return (Criteria) this;
		}

		public Criteria andChromLessThan(String value) {
			addCriterion("chrom <", value, "chrom");
			return (Criteria) this;
		}

		public Criteria andChromLessThanOrEqualTo(String value) {
			addCriterion("chrom <=", value, "chrom");
			return (Criteria) this;
		}

		public Criteria andChromLike(String value) {
			addCriterion("chrom like", value, "chrom");
			return (Criteria) this;
		}

		public Criteria andChromNotLike(String value) {
			addCriterion("chrom not like", value, "chrom");
			return (Criteria) this;
		}

		public Criteria andChromIn(List<String> values) {
			addCriterion("chrom in", values, "chrom");
			return (Criteria) this;
		}

		public Criteria andChromNotIn(List<String> values) {
			addCriterion("chrom not in", values, "chrom");
			return (Criteria) this;
		}

		public Criteria andChromBetween(String value1, String value2) {
			addCriterion("chrom between", value1, value2, "chrom");
			return (Criteria) this;
		}

		public Criteria andChromNotBetween(String value1, String value2) {
			addCriterion("chrom not between", value1, value2, "chrom");
			return (Criteria) this;
		}

		public Criteria andPstIsNull() {
			addCriterion("pst is null");
			return (Criteria) this;
		}

		public Criteria andPstIsNotNull() {
			addCriterion("pst is not null");
			return (Criteria) this;
		}

		public Criteria andPstEqualTo(Integer value) {
			addCriterion("pst =", value, "pst");
			return (Criteria) this;
		}

		public Criteria andPstNotEqualTo(Integer value) {
			addCriterion("pst <>", value, "pst");
			return (Criteria) this;
		}

		public Criteria andPstGreaterThan(Integer value) {
			addCriterion("pst >", value, "pst");
			return (Criteria) this;
		}

		public Criteria andPstGreaterThanOrEqualTo(Integer value) {
			addCriterion("pst >=", value, "pst");
			return (Criteria) this;
		}

		public Criteria andPstLessThan(Integer value) {
			addCriterion("pst <", value, "pst");
			return (Criteria) this;
		}

		public Criteria andPstLessThanOrEqualTo(Integer value) {
			addCriterion("pst <=", value, "pst");
			return (Criteria) this;
		}

		public Criteria andPstIn(List<Integer> values) {
			addCriterion("pst in", values, "pst");
			return (Criteria) this;
		}

		public Criteria andPstNotIn(List<Integer> values) {
			addCriterion("pst not in", values, "pst");
			return (Criteria) this;
		}

		public Criteria andPstBetween(Integer value1, Integer value2) {
			addCriterion("pst between", value1, value2, "pst");
			return (Criteria) this;
		}

		public Criteria andPstNotBetween(Integer value1, Integer value2) {
			addCriterion("pst not between", value1, value2, "pst");
			return (Criteria) this;
		}

		public Criteria andPendIsNull() {
			addCriterion("pend is null");
			return (Criteria) this;
		}

		public Criteria andPendIsNotNull() {
			addCriterion("pend is not null");
			return (Criteria) this;
		}

		public Criteria andPendEqualTo(Integer value) {
			addCriterion("pend =", value, "pend");
			return (Criteria) this;
		}

		public Criteria andPendNotEqualTo(Integer value) {
			addCriterion("pend <>", value, "pend");
			return (Criteria) this;
		}

		public Criteria andPendGreaterThan(Integer value) {
			addCriterion("pend >", value, "pend");
			return (Criteria) this;
		}

		public Criteria andPendGreaterThanOrEqualTo(Integer value) {
			addCriterion("pend >=", value, "pend");
			return (Criteria) this;
		}

		public Criteria andPendLessThan(Integer value) {
			addCriterion("pend <", value, "pend");
			return (Criteria) this;
		}

		public Criteria andPendLessThanOrEqualTo(Integer value) {
			addCriterion("pend <=", value, "pend");
			return (Criteria) this;
		}

		public Criteria andPendIn(List<Integer> values) {
			addCriterion("pend in", values, "pend");
			return (Criteria) this;
		}

		public Criteria andPendNotIn(List<Integer> values) {
			addCriterion("pend not in", values, "pend");
			return (Criteria) this;
		}

		public Criteria andPendBetween(Integer value1, Integer value2) {
			addCriterion("pend between", value1, value2, "pend");
			return (Criteria) this;
		}

		public Criteria andPendNotBetween(Integer value1, Integer value2) {
			addCriterion("pend not between", value1, value2, "pend");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andFprimerIsNull() {
			addCriterion("fprimer is null");
			return (Criteria) this;
		}

		public Criteria andFprimerIsNotNull() {
			addCriterion("fprimer is not null");
			return (Criteria) this;
		}

		public Criteria andFprimerEqualTo(String value) {
			addCriterion("fprimer =", value, "fprimer");
			return (Criteria) this;
		}

		public Criteria andFprimerNotEqualTo(String value) {
			addCriterion("fprimer <>", value, "fprimer");
			return (Criteria) this;
		}

		public Criteria andFprimerGreaterThan(String value) {
			addCriterion("fprimer >", value, "fprimer");
			return (Criteria) this;
		}

		public Criteria andFprimerGreaterThanOrEqualTo(String value) {
			addCriterion("fprimer >=", value, "fprimer");
			return (Criteria) this;
		}

		public Criteria andFprimerLessThan(String value) {
			addCriterion("fprimer <", value, "fprimer");
			return (Criteria) this;
		}

		public Criteria andFprimerLessThanOrEqualTo(String value) {
			addCriterion("fprimer <=", value, "fprimer");
			return (Criteria) this;
		}

		public Criteria andFprimerLike(String value) {
			addCriterion("fprimer like", value, "fprimer");
			return (Criteria) this;
		}

		public Criteria andFprimerNotLike(String value) {
			addCriterion("fprimer not like", value, "fprimer");
			return (Criteria) this;
		}

		public Criteria andFprimerIn(List<String> values) {
			addCriterion("fprimer in", values, "fprimer");
			return (Criteria) this;
		}

		public Criteria andFprimerNotIn(List<String> values) {
			addCriterion("fprimer not in", values, "fprimer");
			return (Criteria) this;
		}

		public Criteria andFprimerBetween(String value1, String value2) {
			addCriterion("fprimer between", value1, value2, "fprimer");
			return (Criteria) this;
		}

		public Criteria andFprimerNotBetween(String value1, String value2) {
			addCriterion("fprimer not between", value1, value2, "fprimer");
			return (Criteria) this;
		}

		public Criteria andRprimerIsNull() {
			addCriterion("rprimer is null");
			return (Criteria) this;
		}

		public Criteria andRprimerIsNotNull() {
			addCriterion("rprimer is not null");
			return (Criteria) this;
		}

		public Criteria andRprimerEqualTo(String value) {
			addCriterion("rprimer =", value, "rprimer");
			return (Criteria) this;
		}

		public Criteria andRprimerNotEqualTo(String value) {
			addCriterion("rprimer <>", value, "rprimer");
			return (Criteria) this;
		}

		public Criteria andRprimerGreaterThan(String value) {
			addCriterion("rprimer >", value, "rprimer");
			return (Criteria) this;
		}

		public Criteria andRprimerGreaterThanOrEqualTo(String value) {
			addCriterion("rprimer >=", value, "rprimer");
			return (Criteria) this;
		}

		public Criteria andRprimerLessThan(String value) {
			addCriterion("rprimer <", value, "rprimer");
			return (Criteria) this;
		}

		public Criteria andRprimerLessThanOrEqualTo(String value) {
			addCriterion("rprimer <=", value, "rprimer");
			return (Criteria) this;
		}

		public Criteria andRprimerLike(String value) {
			addCriterion("rprimer like", value, "rprimer");
			return (Criteria) this;
		}

		public Criteria andRprimerNotLike(String value) {
			addCriterion("rprimer not like", value, "rprimer");
			return (Criteria) this;
		}

		public Criteria andRprimerIn(List<String> values) {
			addCriterion("rprimer in", values, "rprimer");
			return (Criteria) this;
		}

		public Criteria andRprimerNotIn(List<String> values) {
			addCriterion("rprimer not in", values, "rprimer");
			return (Criteria) this;
		}

		public Criteria andRprimerBetween(String value1, String value2) {
			addCriterion("rprimer between", value1, value2, "rprimer");
			return (Criteria) this;
		}

		public Criteria andRprimerNotBetween(String value1, String value2) {
			addCriterion("rprimer not between", value1, value2, "rprimer");
			return (Criteria) this;
		}

		public Criteria andPcrlenIsNull() {
			addCriterion("pcrLen is null");
			return (Criteria) this;
		}

		public Criteria andPcrlenIsNotNull() {
			addCriterion("pcrLen is not null");
			return (Criteria) this;
		}

		public Criteria andPcrlenEqualTo(Integer value) {
			addCriterion("pcrLen =", value, "pcrlen");
			return (Criteria) this;
		}

		public Criteria andPcrlenNotEqualTo(Integer value) {
			addCriterion("pcrLen <>", value, "pcrlen");
			return (Criteria) this;
		}

		public Criteria andPcrlenGreaterThan(Integer value) {
			addCriterion("pcrLen >", value, "pcrlen");
			return (Criteria) this;
		}

		public Criteria andPcrlenGreaterThanOrEqualTo(Integer value) {
			addCriterion("pcrLen >=", value, "pcrlen");
			return (Criteria) this;
		}

		public Criteria andPcrlenLessThan(Integer value) {
			addCriterion("pcrLen <", value, "pcrlen");
			return (Criteria) this;
		}

		public Criteria andPcrlenLessThanOrEqualTo(Integer value) {
			addCriterion("pcrLen <=", value, "pcrlen");
			return (Criteria) this;
		}

		public Criteria andPcrlenIn(List<Integer> values) {
			addCriterion("pcrLen in", values, "pcrlen");
			return (Criteria) this;
		}

		public Criteria andPcrlenNotIn(List<Integer> values) {
			addCriterion("pcrLen not in", values, "pcrlen");
			return (Criteria) this;
		}

		public Criteria andPcrlenBetween(Integer value1, Integer value2) {
			addCriterion("pcrLen between", value1, value2, "pcrlen");
			return (Criteria) this;
		}

		public Criteria andPcrlenNotBetween(Integer value1, Integer value2) {
			addCriterion("pcrLen not between", value1, value2, "pcrlen");
			return (Criteria) this;
		}

		public Criteria andMarkertypeIsNull() {
			addCriterion("markerType is null");
			return (Criteria) this;
		}

		public Criteria andMarkertypeIsNotNull() {
			addCriterion("markerType is not null");
			return (Criteria) this;
		}

		public Criteria andMarkertypeEqualTo(String value) {
			addCriterion("markerType =", value, "markertype");
			return (Criteria) this;
		}

		public Criteria andMarkertypeNotEqualTo(String value) {
			addCriterion("markerType <>", value, "markertype");
			return (Criteria) this;
		}

		public Criteria andMarkertypeGreaterThan(String value) {
			addCriterion("markerType >", value, "markertype");
			return (Criteria) this;
		}

		public Criteria andMarkertypeGreaterThanOrEqualTo(String value) {
			addCriterion("markerType >=", value, "markertype");
			return (Criteria) this;
		}

		public Criteria andMarkertypeLessThan(String value) {
			addCriterion("markerType <", value, "markertype");
			return (Criteria) this;
		}

		public Criteria andMarkertypeLessThanOrEqualTo(String value) {
			addCriterion("markerType <=", value, "markertype");
			return (Criteria) this;
		}

		public Criteria andMarkertypeLike(String value) {
			addCriterion("markerType like", value, "markertype");
			return (Criteria) this;
		}

		public Criteria andMarkertypeNotLike(String value) {
			addCriterion("markerType not like", value, "markertype");
			return (Criteria) this;
		}

		public Criteria andMarkertypeIn(List<String> values) {
			addCriterion("markerType in", values, "markertype");
			return (Criteria) this;
		}

		public Criteria andMarkertypeNotIn(List<String> values) {
			addCriterion("markerType not in", values, "markertype");
			return (Criteria) this;
		}

		public Criteria andMarkertypeBetween(String value1, String value2) {
			addCriterion("markerType between", value1, value2, "markertype");
			return (Criteria) this;
		}

		public Criteria andMarkertypeNotBetween(String value1, String value2) {
			addCriterion("markerType not between", value1, value2, "markertype");
			return (Criteria) this;
		}

		public Criteria andTraitIsNull() {
			addCriterion("trait is null");
			return (Criteria) this;
		}

		public Criteria andTraitIsNotNull() {
			addCriterion("trait is not null");
			return (Criteria) this;
		}

		public Criteria andTraitEqualTo(String value) {
			addCriterion("trait =", value, "trait");
			return (Criteria) this;
		}

		public Criteria andTraitNotEqualTo(String value) {
			addCriterion("trait <>", value, "trait");
			return (Criteria) this;
		}

		public Criteria andTraitGreaterThan(String value) {
			addCriterion("trait >", value, "trait");
			return (Criteria) this;
		}

		public Criteria andTraitGreaterThanOrEqualTo(String value) {
			addCriterion("trait >=", value, "trait");
			return (Criteria) this;
		}

		public Criteria andTraitLessThan(String value) {
			addCriterion("trait <", value, "trait");
			return (Criteria) this;
		}

		public Criteria andTraitLessThanOrEqualTo(String value) {
			addCriterion("trait <=", value, "trait");
			return (Criteria) this;
		}

		public Criteria andTraitLike(String value) {
			addCriterion("trait like", value, "trait");
			return (Criteria) this;
		}

		public Criteria andTraitNotLike(String value) {
			addCriterion("trait not like", value, "trait");
			return (Criteria) this;
		}

		public Criteria andTraitIn(List<String> values) {
			addCriterion("trait in", values, "trait");
			return (Criteria) this;
		}

		public Criteria andTraitNotIn(List<String> values) {
			addCriterion("trait not in", values, "trait");
			return (Criteria) this;
		}

		public Criteria andTraitBetween(String value1, String value2) {
			addCriterion("trait between", value1, value2, "trait");
			return (Criteria) this;
		}

		public Criteria andTraitNotBetween(String value1, String value2) {
			addCriterion("trait not between", value1, value2, "trait");
			return (Criteria) this;
		}

		public Criteria andAuthorIsNull() {
			addCriterion("author is null");
			return (Criteria) this;
		}

		public Criteria andAuthorIsNotNull() {
			addCriterion("author is not null");
			return (Criteria) this;
		}

		public Criteria andAuthorEqualTo(String value) {
			addCriterion("author =", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotEqualTo(String value) {
			addCriterion("author <>", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorGreaterThan(String value) {
			addCriterion("author >", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorGreaterThanOrEqualTo(String value) {
			addCriterion("author >=", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorLessThan(String value) {
			addCriterion("author <", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorLessThanOrEqualTo(String value) {
			addCriterion("author <=", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorLike(String value) {
			addCriterion("author like", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotLike(String value) {
			addCriterion("author not like", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorIn(List<String> values) {
			addCriterion("author in", values, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotIn(List<String> values) {
			addCriterion("author not in", values, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorBetween(String value1, String value2) {
			addCriterion("author between", value1, value2, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotBetween(String value1, String value2) {
			addCriterion("author not between", value1, value2, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorIdxIsNull() {
			addCriterion("author_idx is null");
			return (Criteria) this;
		}

		public Criteria andAuthorIdxIsNotNull() {
			addCriterion("author_idx is not null");
			return (Criteria) this;
		}

		public Criteria andAuthorIdxEqualTo(Integer value) {
			addCriterion("author_idx =", value, "authorIdx");
			return (Criteria) this;
		}

		public Criteria andAuthorIdxNotEqualTo(Integer value) {
			addCriterion("author_idx <>", value, "authorIdx");
			return (Criteria) this;
		}

		public Criteria andAuthorIdxGreaterThan(Integer value) {
			addCriterion("author_idx >", value, "authorIdx");
			return (Criteria) this;
		}

		public Criteria andAuthorIdxGreaterThanOrEqualTo(Integer value) {
			addCriterion("author_idx >=", value, "authorIdx");
			return (Criteria) this;
		}

		public Criteria andAuthorIdxLessThan(Integer value) {
			addCriterion("author_idx <", value, "authorIdx");
			return (Criteria) this;
		}

		public Criteria andAuthorIdxLessThanOrEqualTo(Integer value) {
			addCriterion("author_idx <=", value, "authorIdx");
			return (Criteria) this;
		}

		public Criteria andAuthorIdxIn(List<Integer> values) {
			addCriterion("author_idx in", values, "authorIdx");
			return (Criteria) this;
		}

		public Criteria andAuthorIdxNotIn(List<Integer> values) {
			addCriterion("author_idx not in", values, "authorIdx");
			return (Criteria) this;
		}

		public Criteria andAuthorIdxBetween(Integer value1, Integer value2) {
			addCriterion("author_idx between", value1, value2, "authorIdx");
			return (Criteria) this;
		}

		public Criteria andAuthorIdxNotBetween(Integer value1, Integer value2) {
			addCriterion("author_idx not between", value1, value2, "authorIdx");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table geneticMap
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table geneticMap
     *
     * @mbggenerated do_not_delete_during_merge Mon Feb 24 16:52:07 KST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}