package kr.re.kribb.model;

public class GeneticMap {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column geneticMap.idx
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private Integer idx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column geneticMap.chrom
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String chrom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column geneticMap.pst
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private Integer pst;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column geneticMap.pend
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private Integer pend;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column geneticMap.name
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column geneticMap.fprimer
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String fprimer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column geneticMap.rprimer
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String rprimer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column geneticMap.pcrLen
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private Integer pcrlen;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column geneticMap.markerType
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String markertype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column geneticMap.trait
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String trait;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column geneticMap.author
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String author;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column geneticMap.author_idx
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private Integer authorIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column geneticMap.link
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String link;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column geneticMap.idx
	 * @return  the value of geneticMap.idx
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public Integer getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column geneticMap.idx
	 * @param idx  the value for geneticMap.idx
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column geneticMap.chrom
	 * @return  the value of geneticMap.chrom
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getChrom() {
		return chrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column geneticMap.chrom
	 * @param chrom  the value for geneticMap.chrom
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setChrom(String chrom) {
		this.chrom = chrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column geneticMap.pst
	 * @return  the value of geneticMap.pst
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public Integer getPst() {
		return pst;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column geneticMap.pst
	 * @param pst  the value for geneticMap.pst
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setPst(Integer pst) {
		this.pst = pst;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column geneticMap.pend
	 * @return  the value of geneticMap.pend
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public Integer getPend() {
		return pend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column geneticMap.pend
	 * @param pend  the value for geneticMap.pend
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setPend(Integer pend) {
		this.pend = pend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column geneticMap.name
	 * @return  the value of geneticMap.name
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column geneticMap.name
	 * @param name  the value for geneticMap.name
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column geneticMap.fprimer
	 * @return  the value of geneticMap.fprimer
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getFprimer() {
		return fprimer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column geneticMap.fprimer
	 * @param fprimer  the value for geneticMap.fprimer
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setFprimer(String fprimer) {
		this.fprimer = fprimer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column geneticMap.rprimer
	 * @return  the value of geneticMap.rprimer
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getRprimer() {
		return rprimer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column geneticMap.rprimer
	 * @param rprimer  the value for geneticMap.rprimer
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setRprimer(String rprimer) {
		this.rprimer = rprimer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column geneticMap.pcrLen
	 * @return  the value of geneticMap.pcrLen
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public Integer getPcrlen() {
		return pcrlen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column geneticMap.pcrLen
	 * @param pcrlen  the value for geneticMap.pcrLen
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setPcrlen(Integer pcrlen) {
		this.pcrlen = pcrlen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column geneticMap.markerType
	 * @return  the value of geneticMap.markerType
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getMarkertype() {
		return markertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column geneticMap.markerType
	 * @param markertype  the value for geneticMap.markerType
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setMarkertype(String markertype) {
		this.markertype = markertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column geneticMap.trait
	 * @return  the value of geneticMap.trait
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getTrait() {
		return trait;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column geneticMap.trait
	 * @param trait  the value for geneticMap.trait
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setTrait(String trait) {
		this.trait = trait;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column geneticMap.author
	 * @return  the value of geneticMap.author
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column geneticMap.author
	 * @param author  the value for geneticMap.author
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setAuthor(String author) {
		this.author = author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column geneticMap.author_idx
	 * @return  the value of geneticMap.author_idx
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public Integer getAuthorIdx() {
		return authorIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column geneticMap.author_idx
	 * @param authorIdx  the value for geneticMap.author_idx
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setAuthorIdx(Integer authorIdx) {
		this.authorIdx = authorIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column geneticMap.link
	 * @return  the value of geneticMap.link
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getLink() {
		return link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column geneticMap.link
	 * @param link  the value for geneticMap.link
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setLink(String link) {
		this.link = link;
	}

	public GeneticMap() {
		this.authorIdx = 1;
	}


}