package kr.re.kribb.model;

public class GeneInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GeneInfo.chrom
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String chrom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GeneInfo.start
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private Integer start;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GeneInfo.end
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private Integer end;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GeneInfo.strand
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String strand;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GeneInfo.gene
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String gene;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GeneInfo.description
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GeneInfo.chrom
	 * @return  the value of GeneInfo.chrom
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getChrom() {
		return chrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GeneInfo.chrom
	 * @param chrom  the value for GeneInfo.chrom
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setChrom(String chrom) {
		this.chrom = chrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GeneInfo.start
	 * @return  the value of GeneInfo.start
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public Integer getStart() {
		return start;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GeneInfo.start
	 * @param start  the value for GeneInfo.start
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setStart(Integer start) {
		this.start = start;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GeneInfo.end
	 * @return  the value of GeneInfo.end
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public Integer getEnd() {
		return end;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GeneInfo.end
	 * @param end  the value for GeneInfo.end
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setEnd(Integer end) {
		this.end = end;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GeneInfo.strand
	 * @return  the value of GeneInfo.strand
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getStrand() {
		return strand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GeneInfo.strand
	 * @param strand  the value for GeneInfo.strand
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setStrand(String strand) {
		this.strand = strand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GeneInfo.gene
	 * @return  the value of GeneInfo.gene
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getGene() {
		return gene;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GeneInfo.gene
	 * @param gene  the value for GeneInfo.gene
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setGene(String gene) {
		this.gene = gene;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GeneInfo.description
	 * @return  the value of GeneInfo.description
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GeneInfo.description
	 * @param description  the value for GeneInfo.description
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}