package kr.re.kribb.model;

public class InDel_Marker implements Marker {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.ID
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.chrom
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String chrom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.loci
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private Integer loci;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.Ref
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String ref;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.ALT
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String alt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0001
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0001;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0002
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0002;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0003
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0003;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0004
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0004;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0005
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0005;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0006
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0006;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0007
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0007;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0008
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0008;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0009
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0009;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0010
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0010;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0011
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0011;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0012
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0012;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0013
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0013;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0014
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0014;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0015
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0015;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0016
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0016;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0017
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0017;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0018
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0018;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0019
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0019;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0020
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0020;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0021
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0021;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0022
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0022;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0023
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0023;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0024
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0024;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0025
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0025;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0026
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0026;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0027
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0027;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0028
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0028;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.K0029
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String k0029;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.genes
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String genes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.tags
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String tags;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.fprimer
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String fprimer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.rprimer
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String rprimer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.ltm
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private Float ltm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.rtm
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private Float rtm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.psize
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private Integer psize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column InDel_Marker.template
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String template;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.ID
	 * @return  the value of InDel_Marker.ID
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.ID
	 * @param id  the value for InDel_Marker.ID
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.chrom
	 * @return  the value of InDel_Marker.chrom
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getChrom() {
		return chrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.chrom
	 * @param chrom  the value for InDel_Marker.chrom
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setChrom(String chrom) {
		this.chrom = chrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.loci
	 * @return  the value of InDel_Marker.loci
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public Integer getLoci() {
		return loci;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.loci
	 * @param loci  the value for InDel_Marker.loci
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setLoci(Integer loci) {
		this.loci = loci;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.Ref
	 * @return  the value of InDel_Marker.Ref
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getRef() {
		return ref;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.Ref
	 * @param ref  the value for InDel_Marker.Ref
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setRef(String ref) {
		this.ref = ref;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.ALT
	 * @return  the value of InDel_Marker.ALT
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getAlt() {
		return alt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.ALT
	 * @param alt  the value for InDel_Marker.ALT
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setAlt(String alt) {
		this.alt = alt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0001
	 * @return  the value of InDel_Marker.K0001
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0001() {
		return k0001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0001
	 * @param k0001  the value for InDel_Marker.K0001
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0001(String k0001) {
		this.k0001 = k0001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0002
	 * @return  the value of InDel_Marker.K0002
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0002() {
		return k0002;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0002
	 * @param k0002  the value for InDel_Marker.K0002
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0002(String k0002) {
		this.k0002 = k0002;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0003
	 * @return  the value of InDel_Marker.K0003
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0003() {
		return k0003;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0003
	 * @param k0003  the value for InDel_Marker.K0003
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0003(String k0003) {
		this.k0003 = k0003;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0004
	 * @return  the value of InDel_Marker.K0004
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0004() {
		return k0004;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0004
	 * @param k0004  the value for InDel_Marker.K0004
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0004(String k0004) {
		this.k0004 = k0004;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0005
	 * @return  the value of InDel_Marker.K0005
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0005() {
		return k0005;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0005
	 * @param k0005  the value for InDel_Marker.K0005
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0005(String k0005) {
		this.k0005 = k0005;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0006
	 * @return  the value of InDel_Marker.K0006
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0006() {
		return k0006;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0006
	 * @param k0006  the value for InDel_Marker.K0006
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0006(String k0006) {
		this.k0006 = k0006;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0007
	 * @return  the value of InDel_Marker.K0007
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0007() {
		return k0007;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0007
	 * @param k0007  the value for InDel_Marker.K0007
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0007(String k0007) {
		this.k0007 = k0007;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0008
	 * @return  the value of InDel_Marker.K0008
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0008() {
		return k0008;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0008
	 * @param k0008  the value for InDel_Marker.K0008
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0008(String k0008) {
		this.k0008 = k0008;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0009
	 * @return  the value of InDel_Marker.K0009
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0009() {
		return k0009;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0009
	 * @param k0009  the value for InDel_Marker.K0009
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0009(String k0009) {
		this.k0009 = k0009;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0010
	 * @return  the value of InDel_Marker.K0010
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0010() {
		return k0010;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0010
	 * @param k0010  the value for InDel_Marker.K0010
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0010(String k0010) {
		this.k0010 = k0010;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0011
	 * @return  the value of InDel_Marker.K0011
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0011() {
		return k0011;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0011
	 * @param k0011  the value for InDel_Marker.K0011
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0011(String k0011) {
		this.k0011 = k0011;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0012
	 * @return  the value of InDel_Marker.K0012
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0012() {
		return k0012;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0012
	 * @param k0012  the value for InDel_Marker.K0012
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0012(String k0012) {
		this.k0012 = k0012;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0013
	 * @return  the value of InDel_Marker.K0013
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0013() {
		return k0013;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0013
	 * @param k0013  the value for InDel_Marker.K0013
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0013(String k0013) {
		this.k0013 = k0013;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0014
	 * @return  the value of InDel_Marker.K0014
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0014() {
		return k0014;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0014
	 * @param k0014  the value for InDel_Marker.K0014
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0014(String k0014) {
		this.k0014 = k0014;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0015
	 * @return  the value of InDel_Marker.K0015
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0015() {
		return k0015;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0015
	 * @param k0015  the value for InDel_Marker.K0015
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0015(String k0015) {
		this.k0015 = k0015;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0016
	 * @return  the value of InDel_Marker.K0016
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0016() {
		return k0016;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0016
	 * @param k0016  the value for InDel_Marker.K0016
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0016(String k0016) {
		this.k0016 = k0016;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0017
	 * @return  the value of InDel_Marker.K0017
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0017() {
		return k0017;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0017
	 * @param k0017  the value for InDel_Marker.K0017
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0017(String k0017) {
		this.k0017 = k0017;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0018
	 * @return  the value of InDel_Marker.K0018
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0018() {
		return k0018;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0018
	 * @param k0018  the value for InDel_Marker.K0018
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0018(String k0018) {
		this.k0018 = k0018;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0019
	 * @return  the value of InDel_Marker.K0019
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0019() {
		return k0019;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0019
	 * @param k0019  the value for InDel_Marker.K0019
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0019(String k0019) {
		this.k0019 = k0019;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0020
	 * @return  the value of InDel_Marker.K0020
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0020() {
		return k0020;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0020
	 * @param k0020  the value for InDel_Marker.K0020
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0020(String k0020) {
		this.k0020 = k0020;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0021
	 * @return  the value of InDel_Marker.K0021
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0021() {
		return k0021;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0021
	 * @param k0021  the value for InDel_Marker.K0021
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0021(String k0021) {
		this.k0021 = k0021;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0022
	 * @return  the value of InDel_Marker.K0022
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0022() {
		return k0022;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0022
	 * @param k0022  the value for InDel_Marker.K0022
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0022(String k0022) {
		this.k0022 = k0022;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0023
	 * @return  the value of InDel_Marker.K0023
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0023() {
		return k0023;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0023
	 * @param k0023  the value for InDel_Marker.K0023
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0023(String k0023) {
		this.k0023 = k0023;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0024
	 * @return  the value of InDel_Marker.K0024
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0024() {
		return k0024;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0024
	 * @param k0024  the value for InDel_Marker.K0024
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0024(String k0024) {
		this.k0024 = k0024;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0025
	 * @return  the value of InDel_Marker.K0025
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0025() {
		return k0025;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0025
	 * @param k0025  the value for InDel_Marker.K0025
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0025(String k0025) {
		this.k0025 = k0025;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0026
	 * @return  the value of InDel_Marker.K0026
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0026() {
		return k0026;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0026
	 * @param k0026  the value for InDel_Marker.K0026
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0026(String k0026) {
		this.k0026 = k0026;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0027
	 * @return  the value of InDel_Marker.K0027
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0027() {
		return k0027;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0027
	 * @param k0027  the value for InDel_Marker.K0027
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0027(String k0027) {
		this.k0027 = k0027;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0028
	 * @return  the value of InDel_Marker.K0028
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0028() {
		return k0028;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0028
	 * @param k0028  the value for InDel_Marker.K0028
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0028(String k0028) {
		this.k0028 = k0028;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.K0029
	 * @return  the value of InDel_Marker.K0029
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getK0029() {
		return k0029;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.K0029
	 * @param k0029  the value for InDel_Marker.K0029
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setK0029(String k0029) {
		this.k0029 = k0029;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.genes
	 * @return  the value of InDel_Marker.genes
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getGenes() {
		return genes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.genes
	 * @param genes  the value for InDel_Marker.genes
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setGenes(String genes) {
		this.genes = genes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.tags
	 * @return  the value of InDel_Marker.tags
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getTags() {
		return tags;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.tags
	 * @param tags  the value for InDel_Marker.tags
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setTags(String tags) {
		this.tags = tags;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.fprimer
	 * @return  the value of InDel_Marker.fprimer
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getFprimer() {
		return fprimer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.fprimer
	 * @param fprimer  the value for InDel_Marker.fprimer
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setFprimer(String fprimer) {
		this.fprimer = fprimer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.rprimer
	 * @return  the value of InDel_Marker.rprimer
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getRprimer() {
		return rprimer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.rprimer
	 * @param rprimer  the value for InDel_Marker.rprimer
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setRprimer(String rprimer) {
		this.rprimer = rprimer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.ltm
	 * @return  the value of InDel_Marker.ltm
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public Float getLtm() {
		return ltm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.ltm
	 * @param ltm  the value for InDel_Marker.ltm
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setLtm(Float ltm) {
		this.ltm = ltm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.rtm
	 * @return  the value of InDel_Marker.rtm
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public Float getRtm() {
		return rtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.rtm
	 * @param rtm  the value for InDel_Marker.rtm
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setRtm(Float rtm) {
		this.rtm = rtm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.psize
	 * @return  the value of InDel_Marker.psize
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public Integer getPsize() {
		return psize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.psize
	 * @param psize  the value for InDel_Marker.psize
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setPsize(Integer psize) {
		this.psize = psize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column InDel_Marker.template
	 * @return  the value of InDel_Marker.template
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getTemplate() {
		return template;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column InDel_Marker.template
	 * @param template  the value for InDel_Marker.template
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setTemplate(String template) {
		this.template = template;
	}

	@Override
	public String getType() {
		// TODO Auto-generated method stub
		return "InDel";
	}
}