package kr.re.kribb.model;

public class Line {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.ID
     *
     * @mbggenerated Sat Feb 22 17:43:26 KST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.GT
     *
     * @mbggenerated Sat Feb 22 17:43:26 KST 2014
     */
    private String gt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.Line
     *
     * @mbggenerated Sat Feb 22 17:43:26 KST 2014
     */
    private String line;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.ID
     *
     * @return the value of line.ID
     *
     * @mbggenerated Sat Feb 22 17:43:26 KST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.ID
     *
     * @param id the value for line.ID
     *
     * @mbggenerated Sat Feb 22 17:43:26 KST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.GT
     *
     * @return the value of line.GT
     *
     * @mbggenerated Sat Feb 22 17:43:26 KST 2014
     */
    public String getGt() {
        return gt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.GT
     *
     * @param gt the value for line.GT
     *
     * @mbggenerated Sat Feb 22 17:43:26 KST 2014
     */
    public void setGt(String gt) {
        this.gt = gt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.Line
     *
     * @return the value of line.Line
     *
     * @mbggenerated Sat Feb 22 17:43:26 KST 2014
     */
    public String getLine() {
        return line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.Line
     *
     * @param line the value for line.Line
     *
     * @mbggenerated Sat Feb 22 17:43:26 KST 2014
     */
    public void setLine(String line) {
        this.line = line;
    }
}