package kr.re.kribb.model;

public interface Marker {

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.ID
	 * @return  the value of SNP_Marker.ID
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract Integer getId();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.ID
	 * @param id  the value for SNP_Marker.ID
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setId(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.chrom
	 * @return  the value of SNP_Marker.chrom
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getChrom();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.chrom
	 * @param chrom  the value for SNP_Marker.chrom
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setChrom(String chrom);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.loci
	 * @return  the value of SNP_Marker.loci
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract Integer getLoci();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.loci
	 * @param loci  the value for SNP_Marker.loci
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setLoci(Integer loci);
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0001
	 * @return  the value of SNP_Marker.K0001
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0001();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0001
	 * @param k0001  the value for SNP_Marker.K0001
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0001(String k0001);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0002
	 * @return  the value of SNP_Marker.K0002
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0002();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0002
	 * @param k0002  the value for SNP_Marker.K0002
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0002(String k0002);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0003
	 * @return  the value of SNP_Marker.K0003
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0003();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0003
	 * @param k0003  the value for SNP_Marker.K0003
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0003(String k0003);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0004
	 * @return  the value of SNP_Marker.K0004
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0004();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0004
	 * @param k0004  the value for SNP_Marker.K0004
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0004(String k0004);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0005
	 * @return  the value of SNP_Marker.K0005
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0005();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0005
	 * @param k0005  the value for SNP_Marker.K0005
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0005(String k0005);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0006
	 * @return  the value of SNP_Marker.K0006
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0006();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0006
	 * @param k0006  the value for SNP_Marker.K0006
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0006(String k0006);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0007
	 * @return  the value of SNP_Marker.K0007
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0007();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0007
	 * @param k0007  the value for SNP_Marker.K0007
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0007(String k0007);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0008
	 * @return  the value of SNP_Marker.K0008
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0008();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0008
	 * @param k0008  the value for SNP_Marker.K0008
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0008(String k0008);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0009
	 * @return  the value of SNP_Marker.K0009
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0009();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0009
	 * @param k0009  the value for SNP_Marker.K0009
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0009(String k0009);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0010
	 * @return  the value of SNP_Marker.K0010
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0010();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0010
	 * @param k0010  the value for SNP_Marker.K0010
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0010(String k0010);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0011
	 * @return  the value of SNP_Marker.K0011
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0011();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0011
	 * @param k0011  the value for SNP_Marker.K0011
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0011(String k0011);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0012
	 * @return  the value of SNP_Marker.K0012
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0012();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0012
	 * @param k0012  the value for SNP_Marker.K0012
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0012(String k0012);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0013
	 * @return  the value of SNP_Marker.K0013
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0013();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0013
	 * @param k0013  the value for SNP_Marker.K0013
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0013(String k0013);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0014
	 * @return  the value of SNP_Marker.K0014
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0014();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0014
	 * @param k0014  the value for SNP_Marker.K0014
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0014(String k0014);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0015
	 * @return  the value of SNP_Marker.K0015
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0015();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0015
	 * @param k0015  the value for SNP_Marker.K0015
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0015(String k0015);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0016
	 * @return  the value of SNP_Marker.K0016
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0016();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0016
	 * @param k0016  the value for SNP_Marker.K0016
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0016(String k0016);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0017
	 * @return  the value of SNP_Marker.K0017
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0017();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0017
	 * @param k0017  the value for SNP_Marker.K0017
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0017(String k0017);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0018
	 * @return  the value of SNP_Marker.K0018
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0018();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0018
	 * @param k0018  the value for SNP_Marker.K0018
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0018(String k0018);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0019
	 * @return  the value of SNP_Marker.K0019
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0019();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0019
	 * @param k0019  the value for SNP_Marker.K0019
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0019(String k0019);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0020
	 * @return  the value of SNP_Marker.K0020
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0020();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0020
	 * @param k0020  the value for SNP_Marker.K0020
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0020(String k0020);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0021
	 * @return  the value of SNP_Marker.K0021
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0021();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0021
	 * @param k0021  the value for SNP_Marker.K0021
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0021(String k0021);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0022
	 * @return  the value of SNP_Marker.K0022
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0022();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0022
	 * @param k0022  the value for SNP_Marker.K0022
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0022(String k0022);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0023
	 * @return  the value of SNP_Marker.K0023
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0023();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0023
	 * @param k0023  the value for SNP_Marker.K0023
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0023(String k0023);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0024
	 * @return  the value of SNP_Marker.K0024
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0024();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0024
	 * @param k0024  the value for SNP_Marker.K0024
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0024(String k0024);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0025
	 * @return  the value of SNP_Marker.K0025
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0025();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0025
	 * @param k0025  the value for SNP_Marker.K0025
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0025(String k0025);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0026
	 * @return  the value of SNP_Marker.K0026
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0026();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0026
	 * @param k0026  the value for SNP_Marker.K0026
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0026(String k0026);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0027
	 * @return  the value of SNP_Marker.K0027
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0027();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0027
	 * @param k0027  the value for SNP_Marker.K0027
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0027(String k0027);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0028
	 * @return  the value of SNP_Marker.K0028
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0028();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0028
	 * @param k0028  the value for SNP_Marker.K0028
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0028(String k0028);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.K0029
	 * @return  the value of SNP_Marker.K0029
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getK0029();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.K0029
	 * @param k0029  the value for SNP_Marker.K0029
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setK0029(String k0029);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.genes
	 * @return  the value of SNP_Marker.genes
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getGenes();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.genes
	 * @param genes  the value for SNP_Marker.genes
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setGenes(String genes);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.tags
	 * @return  the value of SNP_Marker.tags
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getTags();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.tags
	 * @param tags  the value for SNP_Marker.tags
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setTags(String tags);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.fprimer
	 * @return  the value of SNP_Marker.fprimer
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getFprimer();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.fprimer
	 * @param fprimer  the value for SNP_Marker.fprimer
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setFprimer(String fprimer);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.rprimer
	 * @return  the value of SNP_Marker.rprimer
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getRprimer();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.rprimer
	 * @param rprimer  the value for SNP_Marker.rprimer
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setRprimer(String rprimer);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.ltm
	 * @return  the value of SNP_Marker.ltm
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract Float getLtm();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.ltm
	 * @param ltm  the value for SNP_Marker.ltm
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setLtm(Float ltm);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.rtm
	 * @return  the value of SNP_Marker.rtm
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract Float getRtm();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.rtm
	 * @param rtm  the value for SNP_Marker.rtm
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setRtm(Float rtm);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SNP_Marker.template
	 * @return  the value of SNP_Marker.template
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract String getTemplate();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SNP_Marker.template
	 * @param template  the value for SNP_Marker.template
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public abstract void setTemplate(String template);
	
	public abstract String getType();

}