package kr.re.kribb.model;

import java.util.ArrayList;
import java.util.List;

public class SnpMarkerExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table SNP_Marker
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table SNP_Marker
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table SNP_Marker
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table SNP_Marker
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	protected int limitStart = -1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table SNP_Marker
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	protected int limitMaxSize = -1;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SNP_Marker
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public SnpMarkerExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SNP_Marker
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SNP_Marker
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SNP_Marker
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SNP_Marker
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SNP_Marker
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SNP_Marker
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SNP_Marker
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SNP_Marker
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SNP_Marker
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SNP_Marker
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SNP_Marker
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setLimitStart(int limitStart) {
		this.limitStart = limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SNP_Marker
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public int getLimitStart() {
		return limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SNP_Marker
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setLimitMaxSize(int limitMaxSize) {
		this.limitMaxSize = limitMaxSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SNP_Marker
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public int getLimitMaxSize() {
		return limitMaxSize;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table SNP_Marker
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andChromIsNull() {
			addCriterion("chrom is null");
			return (Criteria) this;
		}

		public Criteria andChromIsNotNull() {
			addCriterion("chrom is not null");
			return (Criteria) this;
		}

		public Criteria andChromEqualTo(String value) {
			addCriterion("chrom =", value, "chrom");
			return (Criteria) this;
		}

		public Criteria andChromNotEqualTo(String value) {
			addCriterion("chrom <>", value, "chrom");
			return (Criteria) this;
		}

		public Criteria andChromGreaterThan(String value) {
			addCriterion("chrom >", value, "chrom");
			return (Criteria) this;
		}

		public Criteria andChromGreaterThanOrEqualTo(String value) {
			addCriterion("chrom >=", value, "chrom");
			return (Criteria) this;
		}

		public Criteria andChromLessThan(String value) {
			addCriterion("chrom <", value, "chrom");
			return (Criteria) this;
		}

		public Criteria andChromLessThanOrEqualTo(String value) {
			addCriterion("chrom <=", value, "chrom");
			return (Criteria) this;
		}

		public Criteria andChromLike(String value) {
			addCriterion("chrom like", value, "chrom");
			return (Criteria) this;
		}

		public Criteria andChromNotLike(String value) {
			addCriterion("chrom not like", value, "chrom");
			return (Criteria) this;
		}

		public Criteria andChromIn(List<String> values) {
			addCriterion("chrom in", values, "chrom");
			return (Criteria) this;
		}

		public Criteria andChromNotIn(List<String> values) {
			addCriterion("chrom not in", values, "chrom");
			return (Criteria) this;
		}

		public Criteria andChromBetween(String value1, String value2) {
			addCriterion("chrom between", value1, value2, "chrom");
			return (Criteria) this;
		}

		public Criteria andChromNotBetween(String value1, String value2) {
			addCriterion("chrom not between", value1, value2, "chrom");
			return (Criteria) this;
		}

		public Criteria andLociIsNull() {
			addCriterion("loci is null");
			return (Criteria) this;
		}

		public Criteria andLociIsNotNull() {
			addCriterion("loci is not null");
			return (Criteria) this;
		}

		public Criteria andLociEqualTo(Integer value) {
			addCriterion("loci =", value, "loci");
			return (Criteria) this;
		}

		public Criteria andLociNotEqualTo(Integer value) {
			addCriterion("loci <>", value, "loci");
			return (Criteria) this;
		}

		public Criteria andLociGreaterThan(Integer value) {
			addCriterion("loci >", value, "loci");
			return (Criteria) this;
		}

		public Criteria andLociGreaterThanOrEqualTo(Integer value) {
			addCriterion("loci >=", value, "loci");
			return (Criteria) this;
		}

		public Criteria andLociLessThan(Integer value) {
			addCriterion("loci <", value, "loci");
			return (Criteria) this;
		}

		public Criteria andLociLessThanOrEqualTo(Integer value) {
			addCriterion("loci <=", value, "loci");
			return (Criteria) this;
		}

		public Criteria andLociIn(List<Integer> values) {
			addCriterion("loci in", values, "loci");
			return (Criteria) this;
		}

		public Criteria andLociNotIn(List<Integer> values) {
			addCriterion("loci not in", values, "loci");
			return (Criteria) this;
		}

		public Criteria andLociBetween(Integer value1, Integer value2) {
			addCriterion("loci between", value1, value2, "loci");
			return (Criteria) this;
		}

		public Criteria andLociNotBetween(Integer value1, Integer value2) {
			addCriterion("loci not between", value1, value2, "loci");
			return (Criteria) this;
		}

		public Criteria andRefIsNull() {
			addCriterion("Ref is null");
			return (Criteria) this;
		}

		public Criteria andRefIsNotNull() {
			addCriterion("Ref is not null");
			return (Criteria) this;
		}

		public Criteria andRefEqualTo(String value) {
			addCriterion("Ref =", value, "ref");
			return (Criteria) this;
		}

		public Criteria andRefNotEqualTo(String value) {
			addCriterion("Ref <>", value, "ref");
			return (Criteria) this;
		}

		public Criteria andRefGreaterThan(String value) {
			addCriterion("Ref >", value, "ref");
			return (Criteria) this;
		}

		public Criteria andRefGreaterThanOrEqualTo(String value) {
			addCriterion("Ref >=", value, "ref");
			return (Criteria) this;
		}

		public Criteria andRefLessThan(String value) {
			addCriterion("Ref <", value, "ref");
			return (Criteria) this;
		}

		public Criteria andRefLessThanOrEqualTo(String value) {
			addCriterion("Ref <=", value, "ref");
			return (Criteria) this;
		}

		public Criteria andRefLike(String value) {
			addCriterion("Ref like", value, "ref");
			return (Criteria) this;
		}

		public Criteria andRefNotLike(String value) {
			addCriterion("Ref not like", value, "ref");
			return (Criteria) this;
		}

		public Criteria andRefIn(List<String> values) {
			addCriterion("Ref in", values, "ref");
			return (Criteria) this;
		}

		public Criteria andRefNotIn(List<String> values) {
			addCriterion("Ref not in", values, "ref");
			return (Criteria) this;
		}

		public Criteria andRefBetween(String value1, String value2) {
			addCriterion("Ref between", value1, value2, "ref");
			return (Criteria) this;
		}

		public Criteria andRefNotBetween(String value1, String value2) {
			addCriterion("Ref not between", value1, value2, "ref");
			return (Criteria) this;
		}

		public Criteria andAltIsNull() {
			addCriterion("ALT is null");
			return (Criteria) this;
		}

		public Criteria andAltIsNotNull() {
			addCriterion("ALT is not null");
			return (Criteria) this;
		}

		public Criteria andAltEqualTo(String value) {
			addCriterion("ALT =", value, "alt");
			return (Criteria) this;
		}

		public Criteria andAltNotEqualTo(String value) {
			addCriterion("ALT <>", value, "alt");
			return (Criteria) this;
		}

		public Criteria andAltGreaterThan(String value) {
			addCriterion("ALT >", value, "alt");
			return (Criteria) this;
		}

		public Criteria andAltGreaterThanOrEqualTo(String value) {
			addCriterion("ALT >=", value, "alt");
			return (Criteria) this;
		}

		public Criteria andAltLessThan(String value) {
			addCriterion("ALT <", value, "alt");
			return (Criteria) this;
		}

		public Criteria andAltLessThanOrEqualTo(String value) {
			addCriterion("ALT <=", value, "alt");
			return (Criteria) this;
		}

		public Criteria andAltLike(String value) {
			addCriterion("ALT like", value, "alt");
			return (Criteria) this;
		}

		public Criteria andAltNotLike(String value) {
			addCriterion("ALT not like", value, "alt");
			return (Criteria) this;
		}

		public Criteria andAltIn(List<String> values) {
			addCriterion("ALT in", values, "alt");
			return (Criteria) this;
		}

		public Criteria andAltNotIn(List<String> values) {
			addCriterion("ALT not in", values, "alt");
			return (Criteria) this;
		}

		public Criteria andAltBetween(String value1, String value2) {
			addCriterion("ALT between", value1, value2, "alt");
			return (Criteria) this;
		}

		public Criteria andAltNotBetween(String value1, String value2) {
			addCriterion("ALT not between", value1, value2, "alt");
			return (Criteria) this;
		}

		public Criteria andK0001IsNull() {
			addCriterion("K0001 is null");
			return (Criteria) this;
		}

		public Criteria andK0001IsNotNull() {
			addCriterion("K0001 is not null");
			return (Criteria) this;
		}

		public Criteria andK0001EqualTo(String value) {
			addCriterion("K0001 =", value, "k0001");
			return (Criteria) this;
		}

		public Criteria andK0001NotEqualTo(String value) {
			addCriterion("K0001 <>", value, "k0001");
			return (Criteria) this;
		}

		public Criteria andK0001GreaterThan(String value) {
			addCriterion("K0001 >", value, "k0001");
			return (Criteria) this;
		}

		public Criteria andK0001GreaterThanOrEqualTo(String value) {
			addCriterion("K0001 >=", value, "k0001");
			return (Criteria) this;
		}

		public Criteria andK0001LessThan(String value) {
			addCriterion("K0001 <", value, "k0001");
			return (Criteria) this;
		}

		public Criteria andK0001LessThanOrEqualTo(String value) {
			addCriterion("K0001 <=", value, "k0001");
			return (Criteria) this;
		}

		public Criteria andK0001Like(String value) {
			addCriterion("K0001 like", value, "k0001");
			return (Criteria) this;
		}

		public Criteria andK0001NotLike(String value) {
			addCriterion("K0001 not like", value, "k0001");
			return (Criteria) this;
		}

		public Criteria andK0001In(List<String> values) {
			addCriterion("K0001 in", values, "k0001");
			return (Criteria) this;
		}

		public Criteria andK0001NotIn(List<String> values) {
			addCriterion("K0001 not in", values, "k0001");
			return (Criteria) this;
		}

		public Criteria andK0001Between(String value1, String value2) {
			addCriterion("K0001 between", value1, value2, "k0001");
			return (Criteria) this;
		}

		public Criteria andK0001NotBetween(String value1, String value2) {
			addCriterion("K0001 not between", value1, value2, "k0001");
			return (Criteria) this;
		}

		public Criteria andK0002IsNull() {
			addCriterion("K0002 is null");
			return (Criteria) this;
		}

		public Criteria andK0002IsNotNull() {
			addCriterion("K0002 is not null");
			return (Criteria) this;
		}

		public Criteria andK0002EqualTo(String value) {
			addCriterion("K0002 =", value, "k0002");
			return (Criteria) this;
		}

		public Criteria andK0002NotEqualTo(String value) {
			addCriterion("K0002 <>", value, "k0002");
			return (Criteria) this;
		}

		public Criteria andK0002GreaterThan(String value) {
			addCriterion("K0002 >", value, "k0002");
			return (Criteria) this;
		}

		public Criteria andK0002GreaterThanOrEqualTo(String value) {
			addCriterion("K0002 >=", value, "k0002");
			return (Criteria) this;
		}

		public Criteria andK0002LessThan(String value) {
			addCriterion("K0002 <", value, "k0002");
			return (Criteria) this;
		}

		public Criteria andK0002LessThanOrEqualTo(String value) {
			addCriterion("K0002 <=", value, "k0002");
			return (Criteria) this;
		}

		public Criteria andK0002Like(String value) {
			addCriterion("K0002 like", value, "k0002");
			return (Criteria) this;
		}

		public Criteria andK0002NotLike(String value) {
			addCriterion("K0002 not like", value, "k0002");
			return (Criteria) this;
		}

		public Criteria andK0002In(List<String> values) {
			addCriterion("K0002 in", values, "k0002");
			return (Criteria) this;
		}

		public Criteria andK0002NotIn(List<String> values) {
			addCriterion("K0002 not in", values, "k0002");
			return (Criteria) this;
		}

		public Criteria andK0002Between(String value1, String value2) {
			addCriterion("K0002 between", value1, value2, "k0002");
			return (Criteria) this;
		}

		public Criteria andK0002NotBetween(String value1, String value2) {
			addCriterion("K0002 not between", value1, value2, "k0002");
			return (Criteria) this;
		}

		public Criteria andK0003IsNull() {
			addCriterion("K0003 is null");
			return (Criteria) this;
		}

		public Criteria andK0003IsNotNull() {
			addCriterion("K0003 is not null");
			return (Criteria) this;
		}

		public Criteria andK0003EqualTo(String value) {
			addCriterion("K0003 =", value, "k0003");
			return (Criteria) this;
		}

		public Criteria andK0003NotEqualTo(String value) {
			addCriterion("K0003 <>", value, "k0003");
			return (Criteria) this;
		}

		public Criteria andK0003GreaterThan(String value) {
			addCriterion("K0003 >", value, "k0003");
			return (Criteria) this;
		}

		public Criteria andK0003GreaterThanOrEqualTo(String value) {
			addCriterion("K0003 >=", value, "k0003");
			return (Criteria) this;
		}

		public Criteria andK0003LessThan(String value) {
			addCriterion("K0003 <", value, "k0003");
			return (Criteria) this;
		}

		public Criteria andK0003LessThanOrEqualTo(String value) {
			addCriterion("K0003 <=", value, "k0003");
			return (Criteria) this;
		}

		public Criteria andK0003Like(String value) {
			addCriterion("K0003 like", value, "k0003");
			return (Criteria) this;
		}

		public Criteria andK0003NotLike(String value) {
			addCriterion("K0003 not like", value, "k0003");
			return (Criteria) this;
		}

		public Criteria andK0003In(List<String> values) {
			addCriterion("K0003 in", values, "k0003");
			return (Criteria) this;
		}

		public Criteria andK0003NotIn(List<String> values) {
			addCriterion("K0003 not in", values, "k0003");
			return (Criteria) this;
		}

		public Criteria andK0003Between(String value1, String value2) {
			addCriterion("K0003 between", value1, value2, "k0003");
			return (Criteria) this;
		}

		public Criteria andK0003NotBetween(String value1, String value2) {
			addCriterion("K0003 not between", value1, value2, "k0003");
			return (Criteria) this;
		}

		public Criteria andK0004IsNull() {
			addCriterion("K0004 is null");
			return (Criteria) this;
		}

		public Criteria andK0004IsNotNull() {
			addCriterion("K0004 is not null");
			return (Criteria) this;
		}

		public Criteria andK0004EqualTo(String value) {
			addCriterion("K0004 =", value, "k0004");
			return (Criteria) this;
		}

		public Criteria andK0004NotEqualTo(String value) {
			addCriterion("K0004 <>", value, "k0004");
			return (Criteria) this;
		}

		public Criteria andK0004GreaterThan(String value) {
			addCriterion("K0004 >", value, "k0004");
			return (Criteria) this;
		}

		public Criteria andK0004GreaterThanOrEqualTo(String value) {
			addCriterion("K0004 >=", value, "k0004");
			return (Criteria) this;
		}

		public Criteria andK0004LessThan(String value) {
			addCriterion("K0004 <", value, "k0004");
			return (Criteria) this;
		}

		public Criteria andK0004LessThanOrEqualTo(String value) {
			addCriterion("K0004 <=", value, "k0004");
			return (Criteria) this;
		}

		public Criteria andK0004Like(String value) {
			addCriterion("K0004 like", value, "k0004");
			return (Criteria) this;
		}

		public Criteria andK0004NotLike(String value) {
			addCriterion("K0004 not like", value, "k0004");
			return (Criteria) this;
		}

		public Criteria andK0004In(List<String> values) {
			addCriterion("K0004 in", values, "k0004");
			return (Criteria) this;
		}

		public Criteria andK0004NotIn(List<String> values) {
			addCriterion("K0004 not in", values, "k0004");
			return (Criteria) this;
		}

		public Criteria andK0004Between(String value1, String value2) {
			addCriterion("K0004 between", value1, value2, "k0004");
			return (Criteria) this;
		}

		public Criteria andK0004NotBetween(String value1, String value2) {
			addCriterion("K0004 not between", value1, value2, "k0004");
			return (Criteria) this;
		}

		public Criteria andK0005IsNull() {
			addCriterion("K0005 is null");
			return (Criteria) this;
		}

		public Criteria andK0005IsNotNull() {
			addCriterion("K0005 is not null");
			return (Criteria) this;
		}

		public Criteria andK0005EqualTo(String value) {
			addCriterion("K0005 =", value, "k0005");
			return (Criteria) this;
		}

		public Criteria andK0005NotEqualTo(String value) {
			addCriterion("K0005 <>", value, "k0005");
			return (Criteria) this;
		}

		public Criteria andK0005GreaterThan(String value) {
			addCriterion("K0005 >", value, "k0005");
			return (Criteria) this;
		}

		public Criteria andK0005GreaterThanOrEqualTo(String value) {
			addCriterion("K0005 >=", value, "k0005");
			return (Criteria) this;
		}

		public Criteria andK0005LessThan(String value) {
			addCriterion("K0005 <", value, "k0005");
			return (Criteria) this;
		}

		public Criteria andK0005LessThanOrEqualTo(String value) {
			addCriterion("K0005 <=", value, "k0005");
			return (Criteria) this;
		}

		public Criteria andK0005Like(String value) {
			addCriterion("K0005 like", value, "k0005");
			return (Criteria) this;
		}

		public Criteria andK0005NotLike(String value) {
			addCriterion("K0005 not like", value, "k0005");
			return (Criteria) this;
		}

		public Criteria andK0005In(List<String> values) {
			addCriterion("K0005 in", values, "k0005");
			return (Criteria) this;
		}

		public Criteria andK0005NotIn(List<String> values) {
			addCriterion("K0005 not in", values, "k0005");
			return (Criteria) this;
		}

		public Criteria andK0005Between(String value1, String value2) {
			addCriterion("K0005 between", value1, value2, "k0005");
			return (Criteria) this;
		}

		public Criteria andK0005NotBetween(String value1, String value2) {
			addCriterion("K0005 not between", value1, value2, "k0005");
			return (Criteria) this;
		}

		public Criteria andK0006IsNull() {
			addCriterion("K0006 is null");
			return (Criteria) this;
		}

		public Criteria andK0006IsNotNull() {
			addCriterion("K0006 is not null");
			return (Criteria) this;
		}

		public Criteria andK0006EqualTo(String value) {
			addCriterion("K0006 =", value, "k0006");
			return (Criteria) this;
		}

		public Criteria andK0006NotEqualTo(String value) {
			addCriterion("K0006 <>", value, "k0006");
			return (Criteria) this;
		}

		public Criteria andK0006GreaterThan(String value) {
			addCriterion("K0006 >", value, "k0006");
			return (Criteria) this;
		}

		public Criteria andK0006GreaterThanOrEqualTo(String value) {
			addCriterion("K0006 >=", value, "k0006");
			return (Criteria) this;
		}

		public Criteria andK0006LessThan(String value) {
			addCriterion("K0006 <", value, "k0006");
			return (Criteria) this;
		}

		public Criteria andK0006LessThanOrEqualTo(String value) {
			addCriterion("K0006 <=", value, "k0006");
			return (Criteria) this;
		}

		public Criteria andK0006Like(String value) {
			addCriterion("K0006 like", value, "k0006");
			return (Criteria) this;
		}

		public Criteria andK0006NotLike(String value) {
			addCriterion("K0006 not like", value, "k0006");
			return (Criteria) this;
		}

		public Criteria andK0006In(List<String> values) {
			addCriterion("K0006 in", values, "k0006");
			return (Criteria) this;
		}

		public Criteria andK0006NotIn(List<String> values) {
			addCriterion("K0006 not in", values, "k0006");
			return (Criteria) this;
		}

		public Criteria andK0006Between(String value1, String value2) {
			addCriterion("K0006 between", value1, value2, "k0006");
			return (Criteria) this;
		}

		public Criteria andK0006NotBetween(String value1, String value2) {
			addCriterion("K0006 not between", value1, value2, "k0006");
			return (Criteria) this;
		}

		public Criteria andK0007IsNull() {
			addCriterion("K0007 is null");
			return (Criteria) this;
		}

		public Criteria andK0007IsNotNull() {
			addCriterion("K0007 is not null");
			return (Criteria) this;
		}

		public Criteria andK0007EqualTo(String value) {
			addCriterion("K0007 =", value, "k0007");
			return (Criteria) this;
		}

		public Criteria andK0007NotEqualTo(String value) {
			addCriterion("K0007 <>", value, "k0007");
			return (Criteria) this;
		}

		public Criteria andK0007GreaterThan(String value) {
			addCriterion("K0007 >", value, "k0007");
			return (Criteria) this;
		}

		public Criteria andK0007GreaterThanOrEqualTo(String value) {
			addCriterion("K0007 >=", value, "k0007");
			return (Criteria) this;
		}

		public Criteria andK0007LessThan(String value) {
			addCriterion("K0007 <", value, "k0007");
			return (Criteria) this;
		}

		public Criteria andK0007LessThanOrEqualTo(String value) {
			addCriterion("K0007 <=", value, "k0007");
			return (Criteria) this;
		}

		public Criteria andK0007Like(String value) {
			addCriterion("K0007 like", value, "k0007");
			return (Criteria) this;
		}

		public Criteria andK0007NotLike(String value) {
			addCriterion("K0007 not like", value, "k0007");
			return (Criteria) this;
		}

		public Criteria andK0007In(List<String> values) {
			addCriterion("K0007 in", values, "k0007");
			return (Criteria) this;
		}

		public Criteria andK0007NotIn(List<String> values) {
			addCriterion("K0007 not in", values, "k0007");
			return (Criteria) this;
		}

		public Criteria andK0007Between(String value1, String value2) {
			addCriterion("K0007 between", value1, value2, "k0007");
			return (Criteria) this;
		}

		public Criteria andK0007NotBetween(String value1, String value2) {
			addCriterion("K0007 not between", value1, value2, "k0007");
			return (Criteria) this;
		}

		public Criteria andK0008IsNull() {
			addCriterion("K0008 is null");
			return (Criteria) this;
		}

		public Criteria andK0008IsNotNull() {
			addCriterion("K0008 is not null");
			return (Criteria) this;
		}

		public Criteria andK0008EqualTo(String value) {
			addCriterion("K0008 =", value, "k0008");
			return (Criteria) this;
		}

		public Criteria andK0008NotEqualTo(String value) {
			addCriterion("K0008 <>", value, "k0008");
			return (Criteria) this;
		}

		public Criteria andK0008GreaterThan(String value) {
			addCriterion("K0008 >", value, "k0008");
			return (Criteria) this;
		}

		public Criteria andK0008GreaterThanOrEqualTo(String value) {
			addCriterion("K0008 >=", value, "k0008");
			return (Criteria) this;
		}

		public Criteria andK0008LessThan(String value) {
			addCriterion("K0008 <", value, "k0008");
			return (Criteria) this;
		}

		public Criteria andK0008LessThanOrEqualTo(String value) {
			addCriterion("K0008 <=", value, "k0008");
			return (Criteria) this;
		}

		public Criteria andK0008Like(String value) {
			addCriterion("K0008 like", value, "k0008");
			return (Criteria) this;
		}

		public Criteria andK0008NotLike(String value) {
			addCriterion("K0008 not like", value, "k0008");
			return (Criteria) this;
		}

		public Criteria andK0008In(List<String> values) {
			addCriterion("K0008 in", values, "k0008");
			return (Criteria) this;
		}

		public Criteria andK0008NotIn(List<String> values) {
			addCriterion("K0008 not in", values, "k0008");
			return (Criteria) this;
		}

		public Criteria andK0008Between(String value1, String value2) {
			addCriterion("K0008 between", value1, value2, "k0008");
			return (Criteria) this;
		}

		public Criteria andK0008NotBetween(String value1, String value2) {
			addCriterion("K0008 not between", value1, value2, "k0008");
			return (Criteria) this;
		}

		public Criteria andK0009IsNull() {
			addCriterion("K0009 is null");
			return (Criteria) this;
		}

		public Criteria andK0009IsNotNull() {
			addCriterion("K0009 is not null");
			return (Criteria) this;
		}

		public Criteria andK0009EqualTo(String value) {
			addCriterion("K0009 =", value, "k0009");
			return (Criteria) this;
		}

		public Criteria andK0009NotEqualTo(String value) {
			addCriterion("K0009 <>", value, "k0009");
			return (Criteria) this;
		}

		public Criteria andK0009GreaterThan(String value) {
			addCriterion("K0009 >", value, "k0009");
			return (Criteria) this;
		}

		public Criteria andK0009GreaterThanOrEqualTo(String value) {
			addCriterion("K0009 >=", value, "k0009");
			return (Criteria) this;
		}

		public Criteria andK0009LessThan(String value) {
			addCriterion("K0009 <", value, "k0009");
			return (Criteria) this;
		}

		public Criteria andK0009LessThanOrEqualTo(String value) {
			addCriterion("K0009 <=", value, "k0009");
			return (Criteria) this;
		}

		public Criteria andK0009Like(String value) {
			addCriterion("K0009 like", value, "k0009");
			return (Criteria) this;
		}

		public Criteria andK0009NotLike(String value) {
			addCriterion("K0009 not like", value, "k0009");
			return (Criteria) this;
		}

		public Criteria andK0009In(List<String> values) {
			addCriterion("K0009 in", values, "k0009");
			return (Criteria) this;
		}

		public Criteria andK0009NotIn(List<String> values) {
			addCriterion("K0009 not in", values, "k0009");
			return (Criteria) this;
		}

		public Criteria andK0009Between(String value1, String value2) {
			addCriterion("K0009 between", value1, value2, "k0009");
			return (Criteria) this;
		}

		public Criteria andK0009NotBetween(String value1, String value2) {
			addCriterion("K0009 not between", value1, value2, "k0009");
			return (Criteria) this;
		}

		public Criteria andK0010IsNull() {
			addCriterion("K0010 is null");
			return (Criteria) this;
		}

		public Criteria andK0010IsNotNull() {
			addCriterion("K0010 is not null");
			return (Criteria) this;
		}

		public Criteria andK0010EqualTo(String value) {
			addCriterion("K0010 =", value, "k0010");
			return (Criteria) this;
		}

		public Criteria andK0010NotEqualTo(String value) {
			addCriterion("K0010 <>", value, "k0010");
			return (Criteria) this;
		}

		public Criteria andK0010GreaterThan(String value) {
			addCriterion("K0010 >", value, "k0010");
			return (Criteria) this;
		}

		public Criteria andK0010GreaterThanOrEqualTo(String value) {
			addCriterion("K0010 >=", value, "k0010");
			return (Criteria) this;
		}

		public Criteria andK0010LessThan(String value) {
			addCriterion("K0010 <", value, "k0010");
			return (Criteria) this;
		}

		public Criteria andK0010LessThanOrEqualTo(String value) {
			addCriterion("K0010 <=", value, "k0010");
			return (Criteria) this;
		}

		public Criteria andK0010Like(String value) {
			addCriterion("K0010 like", value, "k0010");
			return (Criteria) this;
		}

		public Criteria andK0010NotLike(String value) {
			addCriterion("K0010 not like", value, "k0010");
			return (Criteria) this;
		}

		public Criteria andK0010In(List<String> values) {
			addCriterion("K0010 in", values, "k0010");
			return (Criteria) this;
		}

		public Criteria andK0010NotIn(List<String> values) {
			addCriterion("K0010 not in", values, "k0010");
			return (Criteria) this;
		}

		public Criteria andK0010Between(String value1, String value2) {
			addCriterion("K0010 between", value1, value2, "k0010");
			return (Criteria) this;
		}

		public Criteria andK0010NotBetween(String value1, String value2) {
			addCriterion("K0010 not between", value1, value2, "k0010");
			return (Criteria) this;
		}

		public Criteria andK0011IsNull() {
			addCriterion("K0011 is null");
			return (Criteria) this;
		}

		public Criteria andK0011IsNotNull() {
			addCriterion("K0011 is not null");
			return (Criteria) this;
		}

		public Criteria andK0011EqualTo(String value) {
			addCriterion("K0011 =", value, "k0011");
			return (Criteria) this;
		}

		public Criteria andK0011NotEqualTo(String value) {
			addCriterion("K0011 <>", value, "k0011");
			return (Criteria) this;
		}

		public Criteria andK0011GreaterThan(String value) {
			addCriterion("K0011 >", value, "k0011");
			return (Criteria) this;
		}

		public Criteria andK0011GreaterThanOrEqualTo(String value) {
			addCriterion("K0011 >=", value, "k0011");
			return (Criteria) this;
		}

		public Criteria andK0011LessThan(String value) {
			addCriterion("K0011 <", value, "k0011");
			return (Criteria) this;
		}

		public Criteria andK0011LessThanOrEqualTo(String value) {
			addCriterion("K0011 <=", value, "k0011");
			return (Criteria) this;
		}

		public Criteria andK0011Like(String value) {
			addCriterion("K0011 like", value, "k0011");
			return (Criteria) this;
		}

		public Criteria andK0011NotLike(String value) {
			addCriterion("K0011 not like", value, "k0011");
			return (Criteria) this;
		}

		public Criteria andK0011In(List<String> values) {
			addCriterion("K0011 in", values, "k0011");
			return (Criteria) this;
		}

		public Criteria andK0011NotIn(List<String> values) {
			addCriterion("K0011 not in", values, "k0011");
			return (Criteria) this;
		}

		public Criteria andK0011Between(String value1, String value2) {
			addCriterion("K0011 between", value1, value2, "k0011");
			return (Criteria) this;
		}

		public Criteria andK0011NotBetween(String value1, String value2) {
			addCriterion("K0011 not between", value1, value2, "k0011");
			return (Criteria) this;
		}

		public Criteria andK0012IsNull() {
			addCriterion("K0012 is null");
			return (Criteria) this;
		}

		public Criteria andK0012IsNotNull() {
			addCriterion("K0012 is not null");
			return (Criteria) this;
		}

		public Criteria andK0012EqualTo(String value) {
			addCriterion("K0012 =", value, "k0012");
			return (Criteria) this;
		}

		public Criteria andK0012NotEqualTo(String value) {
			addCriterion("K0012 <>", value, "k0012");
			return (Criteria) this;
		}

		public Criteria andK0012GreaterThan(String value) {
			addCriterion("K0012 >", value, "k0012");
			return (Criteria) this;
		}

		public Criteria andK0012GreaterThanOrEqualTo(String value) {
			addCriterion("K0012 >=", value, "k0012");
			return (Criteria) this;
		}

		public Criteria andK0012LessThan(String value) {
			addCriterion("K0012 <", value, "k0012");
			return (Criteria) this;
		}

		public Criteria andK0012LessThanOrEqualTo(String value) {
			addCriterion("K0012 <=", value, "k0012");
			return (Criteria) this;
		}

		public Criteria andK0012Like(String value) {
			addCriterion("K0012 like", value, "k0012");
			return (Criteria) this;
		}

		public Criteria andK0012NotLike(String value) {
			addCriterion("K0012 not like", value, "k0012");
			return (Criteria) this;
		}

		public Criteria andK0012In(List<String> values) {
			addCriterion("K0012 in", values, "k0012");
			return (Criteria) this;
		}

		public Criteria andK0012NotIn(List<String> values) {
			addCriterion("K0012 not in", values, "k0012");
			return (Criteria) this;
		}

		public Criteria andK0012Between(String value1, String value2) {
			addCriterion("K0012 between", value1, value2, "k0012");
			return (Criteria) this;
		}

		public Criteria andK0012NotBetween(String value1, String value2) {
			addCriterion("K0012 not between", value1, value2, "k0012");
			return (Criteria) this;
		}

		public Criteria andK0013IsNull() {
			addCriterion("K0013 is null");
			return (Criteria) this;
		}

		public Criteria andK0013IsNotNull() {
			addCriterion("K0013 is not null");
			return (Criteria) this;
		}

		public Criteria andK0013EqualTo(String value) {
			addCriterion("K0013 =", value, "k0013");
			return (Criteria) this;
		}

		public Criteria andK0013NotEqualTo(String value) {
			addCriterion("K0013 <>", value, "k0013");
			return (Criteria) this;
		}

		public Criteria andK0013GreaterThan(String value) {
			addCriterion("K0013 >", value, "k0013");
			return (Criteria) this;
		}

		public Criteria andK0013GreaterThanOrEqualTo(String value) {
			addCriterion("K0013 >=", value, "k0013");
			return (Criteria) this;
		}

		public Criteria andK0013LessThan(String value) {
			addCriterion("K0013 <", value, "k0013");
			return (Criteria) this;
		}

		public Criteria andK0013LessThanOrEqualTo(String value) {
			addCriterion("K0013 <=", value, "k0013");
			return (Criteria) this;
		}

		public Criteria andK0013Like(String value) {
			addCriterion("K0013 like", value, "k0013");
			return (Criteria) this;
		}

		public Criteria andK0013NotLike(String value) {
			addCriterion("K0013 not like", value, "k0013");
			return (Criteria) this;
		}

		public Criteria andK0013In(List<String> values) {
			addCriterion("K0013 in", values, "k0013");
			return (Criteria) this;
		}

		public Criteria andK0013NotIn(List<String> values) {
			addCriterion("K0013 not in", values, "k0013");
			return (Criteria) this;
		}

		public Criteria andK0013Between(String value1, String value2) {
			addCriterion("K0013 between", value1, value2, "k0013");
			return (Criteria) this;
		}

		public Criteria andK0013NotBetween(String value1, String value2) {
			addCriterion("K0013 not between", value1, value2, "k0013");
			return (Criteria) this;
		}

		public Criteria andK0014IsNull() {
			addCriterion("K0014 is null");
			return (Criteria) this;
		}

		public Criteria andK0014IsNotNull() {
			addCriterion("K0014 is not null");
			return (Criteria) this;
		}

		public Criteria andK0014EqualTo(String value) {
			addCriterion("K0014 =", value, "k0014");
			return (Criteria) this;
		}

		public Criteria andK0014NotEqualTo(String value) {
			addCriterion("K0014 <>", value, "k0014");
			return (Criteria) this;
		}

		public Criteria andK0014GreaterThan(String value) {
			addCriterion("K0014 >", value, "k0014");
			return (Criteria) this;
		}

		public Criteria andK0014GreaterThanOrEqualTo(String value) {
			addCriterion("K0014 >=", value, "k0014");
			return (Criteria) this;
		}

		public Criteria andK0014LessThan(String value) {
			addCriterion("K0014 <", value, "k0014");
			return (Criteria) this;
		}

		public Criteria andK0014LessThanOrEqualTo(String value) {
			addCriterion("K0014 <=", value, "k0014");
			return (Criteria) this;
		}

		public Criteria andK0014Like(String value) {
			addCriterion("K0014 like", value, "k0014");
			return (Criteria) this;
		}

		public Criteria andK0014NotLike(String value) {
			addCriterion("K0014 not like", value, "k0014");
			return (Criteria) this;
		}

		public Criteria andK0014In(List<String> values) {
			addCriterion("K0014 in", values, "k0014");
			return (Criteria) this;
		}

		public Criteria andK0014NotIn(List<String> values) {
			addCriterion("K0014 not in", values, "k0014");
			return (Criteria) this;
		}

		public Criteria andK0014Between(String value1, String value2) {
			addCriterion("K0014 between", value1, value2, "k0014");
			return (Criteria) this;
		}

		public Criteria andK0014NotBetween(String value1, String value2) {
			addCriterion("K0014 not between", value1, value2, "k0014");
			return (Criteria) this;
		}

		public Criteria andK0015IsNull() {
			addCriterion("K0015 is null");
			return (Criteria) this;
		}

		public Criteria andK0015IsNotNull() {
			addCriterion("K0015 is not null");
			return (Criteria) this;
		}

		public Criteria andK0015EqualTo(String value) {
			addCriterion("K0015 =", value, "k0015");
			return (Criteria) this;
		}

		public Criteria andK0015NotEqualTo(String value) {
			addCriterion("K0015 <>", value, "k0015");
			return (Criteria) this;
		}

		public Criteria andK0015GreaterThan(String value) {
			addCriterion("K0015 >", value, "k0015");
			return (Criteria) this;
		}

		public Criteria andK0015GreaterThanOrEqualTo(String value) {
			addCriterion("K0015 >=", value, "k0015");
			return (Criteria) this;
		}

		public Criteria andK0015LessThan(String value) {
			addCriterion("K0015 <", value, "k0015");
			return (Criteria) this;
		}

		public Criteria andK0015LessThanOrEqualTo(String value) {
			addCriterion("K0015 <=", value, "k0015");
			return (Criteria) this;
		}

		public Criteria andK0015Like(String value) {
			addCriterion("K0015 like", value, "k0015");
			return (Criteria) this;
		}

		public Criteria andK0015NotLike(String value) {
			addCriterion("K0015 not like", value, "k0015");
			return (Criteria) this;
		}

		public Criteria andK0015In(List<String> values) {
			addCriterion("K0015 in", values, "k0015");
			return (Criteria) this;
		}

		public Criteria andK0015NotIn(List<String> values) {
			addCriterion("K0015 not in", values, "k0015");
			return (Criteria) this;
		}

		public Criteria andK0015Between(String value1, String value2) {
			addCriterion("K0015 between", value1, value2, "k0015");
			return (Criteria) this;
		}

		public Criteria andK0015NotBetween(String value1, String value2) {
			addCriterion("K0015 not between", value1, value2, "k0015");
			return (Criteria) this;
		}

		public Criteria andK0016IsNull() {
			addCriterion("K0016 is null");
			return (Criteria) this;
		}

		public Criteria andK0016IsNotNull() {
			addCriterion("K0016 is not null");
			return (Criteria) this;
		}

		public Criteria andK0016EqualTo(String value) {
			addCriterion("K0016 =", value, "k0016");
			return (Criteria) this;
		}

		public Criteria andK0016NotEqualTo(String value) {
			addCriterion("K0016 <>", value, "k0016");
			return (Criteria) this;
		}

		public Criteria andK0016GreaterThan(String value) {
			addCriterion("K0016 >", value, "k0016");
			return (Criteria) this;
		}

		public Criteria andK0016GreaterThanOrEqualTo(String value) {
			addCriterion("K0016 >=", value, "k0016");
			return (Criteria) this;
		}

		public Criteria andK0016LessThan(String value) {
			addCriterion("K0016 <", value, "k0016");
			return (Criteria) this;
		}

		public Criteria andK0016LessThanOrEqualTo(String value) {
			addCriterion("K0016 <=", value, "k0016");
			return (Criteria) this;
		}

		public Criteria andK0016Like(String value) {
			addCriterion("K0016 like", value, "k0016");
			return (Criteria) this;
		}

		public Criteria andK0016NotLike(String value) {
			addCriterion("K0016 not like", value, "k0016");
			return (Criteria) this;
		}

		public Criteria andK0016In(List<String> values) {
			addCriterion("K0016 in", values, "k0016");
			return (Criteria) this;
		}

		public Criteria andK0016NotIn(List<String> values) {
			addCriterion("K0016 not in", values, "k0016");
			return (Criteria) this;
		}

		public Criteria andK0016Between(String value1, String value2) {
			addCriterion("K0016 between", value1, value2, "k0016");
			return (Criteria) this;
		}

		public Criteria andK0016NotBetween(String value1, String value2) {
			addCriterion("K0016 not between", value1, value2, "k0016");
			return (Criteria) this;
		}

		public Criteria andK0017IsNull() {
			addCriterion("K0017 is null");
			return (Criteria) this;
		}

		public Criteria andK0017IsNotNull() {
			addCriterion("K0017 is not null");
			return (Criteria) this;
		}

		public Criteria andK0017EqualTo(String value) {
			addCriterion("K0017 =", value, "k0017");
			return (Criteria) this;
		}

		public Criteria andK0017NotEqualTo(String value) {
			addCriterion("K0017 <>", value, "k0017");
			return (Criteria) this;
		}

		public Criteria andK0017GreaterThan(String value) {
			addCriterion("K0017 >", value, "k0017");
			return (Criteria) this;
		}

		public Criteria andK0017GreaterThanOrEqualTo(String value) {
			addCriterion("K0017 >=", value, "k0017");
			return (Criteria) this;
		}

		public Criteria andK0017LessThan(String value) {
			addCriterion("K0017 <", value, "k0017");
			return (Criteria) this;
		}

		public Criteria andK0017LessThanOrEqualTo(String value) {
			addCriterion("K0017 <=", value, "k0017");
			return (Criteria) this;
		}

		public Criteria andK0017Like(String value) {
			addCriterion("K0017 like", value, "k0017");
			return (Criteria) this;
		}

		public Criteria andK0017NotLike(String value) {
			addCriterion("K0017 not like", value, "k0017");
			return (Criteria) this;
		}

		public Criteria andK0017In(List<String> values) {
			addCriterion("K0017 in", values, "k0017");
			return (Criteria) this;
		}

		public Criteria andK0017NotIn(List<String> values) {
			addCriterion("K0017 not in", values, "k0017");
			return (Criteria) this;
		}

		public Criteria andK0017Between(String value1, String value2) {
			addCriterion("K0017 between", value1, value2, "k0017");
			return (Criteria) this;
		}

		public Criteria andK0017NotBetween(String value1, String value2) {
			addCriterion("K0017 not between", value1, value2, "k0017");
			return (Criteria) this;
		}

		public Criteria andK0018IsNull() {
			addCriterion("K0018 is null");
			return (Criteria) this;
		}

		public Criteria andK0018IsNotNull() {
			addCriterion("K0018 is not null");
			return (Criteria) this;
		}

		public Criteria andK0018EqualTo(String value) {
			addCriterion("K0018 =", value, "k0018");
			return (Criteria) this;
		}

		public Criteria andK0018NotEqualTo(String value) {
			addCriterion("K0018 <>", value, "k0018");
			return (Criteria) this;
		}

		public Criteria andK0018GreaterThan(String value) {
			addCriterion("K0018 >", value, "k0018");
			return (Criteria) this;
		}

		public Criteria andK0018GreaterThanOrEqualTo(String value) {
			addCriterion("K0018 >=", value, "k0018");
			return (Criteria) this;
		}

		public Criteria andK0018LessThan(String value) {
			addCriterion("K0018 <", value, "k0018");
			return (Criteria) this;
		}

		public Criteria andK0018LessThanOrEqualTo(String value) {
			addCriterion("K0018 <=", value, "k0018");
			return (Criteria) this;
		}

		public Criteria andK0018Like(String value) {
			addCriterion("K0018 like", value, "k0018");
			return (Criteria) this;
		}

		public Criteria andK0018NotLike(String value) {
			addCriterion("K0018 not like", value, "k0018");
			return (Criteria) this;
		}

		public Criteria andK0018In(List<String> values) {
			addCriterion("K0018 in", values, "k0018");
			return (Criteria) this;
		}

		public Criteria andK0018NotIn(List<String> values) {
			addCriterion("K0018 not in", values, "k0018");
			return (Criteria) this;
		}

		public Criteria andK0018Between(String value1, String value2) {
			addCriterion("K0018 between", value1, value2, "k0018");
			return (Criteria) this;
		}

		public Criteria andK0018NotBetween(String value1, String value2) {
			addCriterion("K0018 not between", value1, value2, "k0018");
			return (Criteria) this;
		}

		public Criteria andK0019IsNull() {
			addCriterion("K0019 is null");
			return (Criteria) this;
		}

		public Criteria andK0019IsNotNull() {
			addCriterion("K0019 is not null");
			return (Criteria) this;
		}

		public Criteria andK0019EqualTo(String value) {
			addCriterion("K0019 =", value, "k0019");
			return (Criteria) this;
		}

		public Criteria andK0019NotEqualTo(String value) {
			addCriterion("K0019 <>", value, "k0019");
			return (Criteria) this;
		}

		public Criteria andK0019GreaterThan(String value) {
			addCriterion("K0019 >", value, "k0019");
			return (Criteria) this;
		}

		public Criteria andK0019GreaterThanOrEqualTo(String value) {
			addCriterion("K0019 >=", value, "k0019");
			return (Criteria) this;
		}

		public Criteria andK0019LessThan(String value) {
			addCriterion("K0019 <", value, "k0019");
			return (Criteria) this;
		}

		public Criteria andK0019LessThanOrEqualTo(String value) {
			addCriterion("K0019 <=", value, "k0019");
			return (Criteria) this;
		}

		public Criteria andK0019Like(String value) {
			addCriterion("K0019 like", value, "k0019");
			return (Criteria) this;
		}

		public Criteria andK0019NotLike(String value) {
			addCriterion("K0019 not like", value, "k0019");
			return (Criteria) this;
		}

		public Criteria andK0019In(List<String> values) {
			addCriterion("K0019 in", values, "k0019");
			return (Criteria) this;
		}

		public Criteria andK0019NotIn(List<String> values) {
			addCriterion("K0019 not in", values, "k0019");
			return (Criteria) this;
		}

		public Criteria andK0019Between(String value1, String value2) {
			addCriterion("K0019 between", value1, value2, "k0019");
			return (Criteria) this;
		}

		public Criteria andK0019NotBetween(String value1, String value2) {
			addCriterion("K0019 not between", value1, value2, "k0019");
			return (Criteria) this;
		}

		public Criteria andK0020IsNull() {
			addCriterion("K0020 is null");
			return (Criteria) this;
		}

		public Criteria andK0020IsNotNull() {
			addCriterion("K0020 is not null");
			return (Criteria) this;
		}

		public Criteria andK0020EqualTo(String value) {
			addCriterion("K0020 =", value, "k0020");
			return (Criteria) this;
		}

		public Criteria andK0020NotEqualTo(String value) {
			addCriterion("K0020 <>", value, "k0020");
			return (Criteria) this;
		}

		public Criteria andK0020GreaterThan(String value) {
			addCriterion("K0020 >", value, "k0020");
			return (Criteria) this;
		}

		public Criteria andK0020GreaterThanOrEqualTo(String value) {
			addCriterion("K0020 >=", value, "k0020");
			return (Criteria) this;
		}

		public Criteria andK0020LessThan(String value) {
			addCriterion("K0020 <", value, "k0020");
			return (Criteria) this;
		}

		public Criteria andK0020LessThanOrEqualTo(String value) {
			addCriterion("K0020 <=", value, "k0020");
			return (Criteria) this;
		}

		public Criteria andK0020Like(String value) {
			addCriterion("K0020 like", value, "k0020");
			return (Criteria) this;
		}

		public Criteria andK0020NotLike(String value) {
			addCriterion("K0020 not like", value, "k0020");
			return (Criteria) this;
		}

		public Criteria andK0020In(List<String> values) {
			addCriterion("K0020 in", values, "k0020");
			return (Criteria) this;
		}

		public Criteria andK0020NotIn(List<String> values) {
			addCriterion("K0020 not in", values, "k0020");
			return (Criteria) this;
		}

		public Criteria andK0020Between(String value1, String value2) {
			addCriterion("K0020 between", value1, value2, "k0020");
			return (Criteria) this;
		}

		public Criteria andK0020NotBetween(String value1, String value2) {
			addCriterion("K0020 not between", value1, value2, "k0020");
			return (Criteria) this;
		}

		public Criteria andK0021IsNull() {
			addCriterion("K0021 is null");
			return (Criteria) this;
		}

		public Criteria andK0021IsNotNull() {
			addCriterion("K0021 is not null");
			return (Criteria) this;
		}

		public Criteria andK0021EqualTo(String value) {
			addCriterion("K0021 =", value, "k0021");
			return (Criteria) this;
		}

		public Criteria andK0021NotEqualTo(String value) {
			addCriterion("K0021 <>", value, "k0021");
			return (Criteria) this;
		}

		public Criteria andK0021GreaterThan(String value) {
			addCriterion("K0021 >", value, "k0021");
			return (Criteria) this;
		}

		public Criteria andK0021GreaterThanOrEqualTo(String value) {
			addCriterion("K0021 >=", value, "k0021");
			return (Criteria) this;
		}

		public Criteria andK0021LessThan(String value) {
			addCriterion("K0021 <", value, "k0021");
			return (Criteria) this;
		}

		public Criteria andK0021LessThanOrEqualTo(String value) {
			addCriterion("K0021 <=", value, "k0021");
			return (Criteria) this;
		}

		public Criteria andK0021Like(String value) {
			addCriterion("K0021 like", value, "k0021");
			return (Criteria) this;
		}

		public Criteria andK0021NotLike(String value) {
			addCriterion("K0021 not like", value, "k0021");
			return (Criteria) this;
		}

		public Criteria andK0021In(List<String> values) {
			addCriterion("K0021 in", values, "k0021");
			return (Criteria) this;
		}

		public Criteria andK0021NotIn(List<String> values) {
			addCriterion("K0021 not in", values, "k0021");
			return (Criteria) this;
		}

		public Criteria andK0021Between(String value1, String value2) {
			addCriterion("K0021 between", value1, value2, "k0021");
			return (Criteria) this;
		}

		public Criteria andK0021NotBetween(String value1, String value2) {
			addCriterion("K0021 not between", value1, value2, "k0021");
			return (Criteria) this;
		}

		public Criteria andK0022IsNull() {
			addCriterion("K0022 is null");
			return (Criteria) this;
		}

		public Criteria andK0022IsNotNull() {
			addCriterion("K0022 is not null");
			return (Criteria) this;
		}

		public Criteria andK0022EqualTo(String value) {
			addCriterion("K0022 =", value, "k0022");
			return (Criteria) this;
		}

		public Criteria andK0022NotEqualTo(String value) {
			addCriterion("K0022 <>", value, "k0022");
			return (Criteria) this;
		}

		public Criteria andK0022GreaterThan(String value) {
			addCriterion("K0022 >", value, "k0022");
			return (Criteria) this;
		}

		public Criteria andK0022GreaterThanOrEqualTo(String value) {
			addCriterion("K0022 >=", value, "k0022");
			return (Criteria) this;
		}

		public Criteria andK0022LessThan(String value) {
			addCriterion("K0022 <", value, "k0022");
			return (Criteria) this;
		}

		public Criteria andK0022LessThanOrEqualTo(String value) {
			addCriterion("K0022 <=", value, "k0022");
			return (Criteria) this;
		}

		public Criteria andK0022Like(String value) {
			addCriterion("K0022 like", value, "k0022");
			return (Criteria) this;
		}

		public Criteria andK0022NotLike(String value) {
			addCriterion("K0022 not like", value, "k0022");
			return (Criteria) this;
		}

		public Criteria andK0022In(List<String> values) {
			addCriterion("K0022 in", values, "k0022");
			return (Criteria) this;
		}

		public Criteria andK0022NotIn(List<String> values) {
			addCriterion("K0022 not in", values, "k0022");
			return (Criteria) this;
		}

		public Criteria andK0022Between(String value1, String value2) {
			addCriterion("K0022 between", value1, value2, "k0022");
			return (Criteria) this;
		}

		public Criteria andK0022NotBetween(String value1, String value2) {
			addCriterion("K0022 not between", value1, value2, "k0022");
			return (Criteria) this;
		}

		public Criteria andK0023IsNull() {
			addCriterion("K0023 is null");
			return (Criteria) this;
		}

		public Criteria andK0023IsNotNull() {
			addCriterion("K0023 is not null");
			return (Criteria) this;
		}

		public Criteria andK0023EqualTo(String value) {
			addCriterion("K0023 =", value, "k0023");
			return (Criteria) this;
		}

		public Criteria andK0023NotEqualTo(String value) {
			addCriterion("K0023 <>", value, "k0023");
			return (Criteria) this;
		}

		public Criteria andK0023GreaterThan(String value) {
			addCriterion("K0023 >", value, "k0023");
			return (Criteria) this;
		}

		public Criteria andK0023GreaterThanOrEqualTo(String value) {
			addCriterion("K0023 >=", value, "k0023");
			return (Criteria) this;
		}

		public Criteria andK0023LessThan(String value) {
			addCriterion("K0023 <", value, "k0023");
			return (Criteria) this;
		}

		public Criteria andK0023LessThanOrEqualTo(String value) {
			addCriterion("K0023 <=", value, "k0023");
			return (Criteria) this;
		}

		public Criteria andK0023Like(String value) {
			addCriterion("K0023 like", value, "k0023");
			return (Criteria) this;
		}

		public Criteria andK0023NotLike(String value) {
			addCriterion("K0023 not like", value, "k0023");
			return (Criteria) this;
		}

		public Criteria andK0023In(List<String> values) {
			addCriterion("K0023 in", values, "k0023");
			return (Criteria) this;
		}

		public Criteria andK0023NotIn(List<String> values) {
			addCriterion("K0023 not in", values, "k0023");
			return (Criteria) this;
		}

		public Criteria andK0023Between(String value1, String value2) {
			addCriterion("K0023 between", value1, value2, "k0023");
			return (Criteria) this;
		}

		public Criteria andK0023NotBetween(String value1, String value2) {
			addCriterion("K0023 not between", value1, value2, "k0023");
			return (Criteria) this;
		}

		public Criteria andK0024IsNull() {
			addCriterion("K0024 is null");
			return (Criteria) this;
		}

		public Criteria andK0024IsNotNull() {
			addCriterion("K0024 is not null");
			return (Criteria) this;
		}

		public Criteria andK0024EqualTo(String value) {
			addCriterion("K0024 =", value, "k0024");
			return (Criteria) this;
		}

		public Criteria andK0024NotEqualTo(String value) {
			addCriterion("K0024 <>", value, "k0024");
			return (Criteria) this;
		}

		public Criteria andK0024GreaterThan(String value) {
			addCriterion("K0024 >", value, "k0024");
			return (Criteria) this;
		}

		public Criteria andK0024GreaterThanOrEqualTo(String value) {
			addCriterion("K0024 >=", value, "k0024");
			return (Criteria) this;
		}

		public Criteria andK0024LessThan(String value) {
			addCriterion("K0024 <", value, "k0024");
			return (Criteria) this;
		}

		public Criteria andK0024LessThanOrEqualTo(String value) {
			addCriterion("K0024 <=", value, "k0024");
			return (Criteria) this;
		}

		public Criteria andK0024Like(String value) {
			addCriterion("K0024 like", value, "k0024");
			return (Criteria) this;
		}

		public Criteria andK0024NotLike(String value) {
			addCriterion("K0024 not like", value, "k0024");
			return (Criteria) this;
		}

		public Criteria andK0024In(List<String> values) {
			addCriterion("K0024 in", values, "k0024");
			return (Criteria) this;
		}

		public Criteria andK0024NotIn(List<String> values) {
			addCriterion("K0024 not in", values, "k0024");
			return (Criteria) this;
		}

		public Criteria andK0024Between(String value1, String value2) {
			addCriterion("K0024 between", value1, value2, "k0024");
			return (Criteria) this;
		}

		public Criteria andK0024NotBetween(String value1, String value2) {
			addCriterion("K0024 not between", value1, value2, "k0024");
			return (Criteria) this;
		}

		public Criteria andK0025IsNull() {
			addCriterion("K0025 is null");
			return (Criteria) this;
		}

		public Criteria andK0025IsNotNull() {
			addCriterion("K0025 is not null");
			return (Criteria) this;
		}

		public Criteria andK0025EqualTo(String value) {
			addCriterion("K0025 =", value, "k0025");
			return (Criteria) this;
		}

		public Criteria andK0025NotEqualTo(String value) {
			addCriterion("K0025 <>", value, "k0025");
			return (Criteria) this;
		}

		public Criteria andK0025GreaterThan(String value) {
			addCriterion("K0025 >", value, "k0025");
			return (Criteria) this;
		}

		public Criteria andK0025GreaterThanOrEqualTo(String value) {
			addCriterion("K0025 >=", value, "k0025");
			return (Criteria) this;
		}

		public Criteria andK0025LessThan(String value) {
			addCriterion("K0025 <", value, "k0025");
			return (Criteria) this;
		}

		public Criteria andK0025LessThanOrEqualTo(String value) {
			addCriterion("K0025 <=", value, "k0025");
			return (Criteria) this;
		}

		public Criteria andK0025Like(String value) {
			addCriterion("K0025 like", value, "k0025");
			return (Criteria) this;
		}

		public Criteria andK0025NotLike(String value) {
			addCriterion("K0025 not like", value, "k0025");
			return (Criteria) this;
		}

		public Criteria andK0025In(List<String> values) {
			addCriterion("K0025 in", values, "k0025");
			return (Criteria) this;
		}

		public Criteria andK0025NotIn(List<String> values) {
			addCriterion("K0025 not in", values, "k0025");
			return (Criteria) this;
		}

		public Criteria andK0025Between(String value1, String value2) {
			addCriterion("K0025 between", value1, value2, "k0025");
			return (Criteria) this;
		}

		public Criteria andK0025NotBetween(String value1, String value2) {
			addCriterion("K0025 not between", value1, value2, "k0025");
			return (Criteria) this;
		}

		public Criteria andK0026IsNull() {
			addCriterion("K0026 is null");
			return (Criteria) this;
		}

		public Criteria andK0026IsNotNull() {
			addCriterion("K0026 is not null");
			return (Criteria) this;
		}

		public Criteria andK0026EqualTo(String value) {
			addCriterion("K0026 =", value, "k0026");
			return (Criteria) this;
		}

		public Criteria andK0026NotEqualTo(String value) {
			addCriterion("K0026 <>", value, "k0026");
			return (Criteria) this;
		}

		public Criteria andK0026GreaterThan(String value) {
			addCriterion("K0026 >", value, "k0026");
			return (Criteria) this;
		}

		public Criteria andK0026GreaterThanOrEqualTo(String value) {
			addCriterion("K0026 >=", value, "k0026");
			return (Criteria) this;
		}

		public Criteria andK0026LessThan(String value) {
			addCriterion("K0026 <", value, "k0026");
			return (Criteria) this;
		}

		public Criteria andK0026LessThanOrEqualTo(String value) {
			addCriterion("K0026 <=", value, "k0026");
			return (Criteria) this;
		}

		public Criteria andK0026Like(String value) {
			addCriterion("K0026 like", value, "k0026");
			return (Criteria) this;
		}

		public Criteria andK0026NotLike(String value) {
			addCriterion("K0026 not like", value, "k0026");
			return (Criteria) this;
		}

		public Criteria andK0026In(List<String> values) {
			addCriterion("K0026 in", values, "k0026");
			return (Criteria) this;
		}

		public Criteria andK0026NotIn(List<String> values) {
			addCriterion("K0026 not in", values, "k0026");
			return (Criteria) this;
		}

		public Criteria andK0026Between(String value1, String value2) {
			addCriterion("K0026 between", value1, value2, "k0026");
			return (Criteria) this;
		}

		public Criteria andK0026NotBetween(String value1, String value2) {
			addCriterion("K0026 not between", value1, value2, "k0026");
			return (Criteria) this;
		}

		public Criteria andK0027IsNull() {
			addCriterion("K0027 is null");
			return (Criteria) this;
		}

		public Criteria andK0027IsNotNull() {
			addCriterion("K0027 is not null");
			return (Criteria) this;
		}

		public Criteria andK0027EqualTo(String value) {
			addCriterion("K0027 =", value, "k0027");
			return (Criteria) this;
		}

		public Criteria andK0027NotEqualTo(String value) {
			addCriterion("K0027 <>", value, "k0027");
			return (Criteria) this;
		}

		public Criteria andK0027GreaterThan(String value) {
			addCriterion("K0027 >", value, "k0027");
			return (Criteria) this;
		}

		public Criteria andK0027GreaterThanOrEqualTo(String value) {
			addCriterion("K0027 >=", value, "k0027");
			return (Criteria) this;
		}

		public Criteria andK0027LessThan(String value) {
			addCriterion("K0027 <", value, "k0027");
			return (Criteria) this;
		}

		public Criteria andK0027LessThanOrEqualTo(String value) {
			addCriterion("K0027 <=", value, "k0027");
			return (Criteria) this;
		}

		public Criteria andK0027Like(String value) {
			addCriterion("K0027 like", value, "k0027");
			return (Criteria) this;
		}

		public Criteria andK0027NotLike(String value) {
			addCriterion("K0027 not like", value, "k0027");
			return (Criteria) this;
		}

		public Criteria andK0027In(List<String> values) {
			addCriterion("K0027 in", values, "k0027");
			return (Criteria) this;
		}

		public Criteria andK0027NotIn(List<String> values) {
			addCriterion("K0027 not in", values, "k0027");
			return (Criteria) this;
		}

		public Criteria andK0027Between(String value1, String value2) {
			addCriterion("K0027 between", value1, value2, "k0027");
			return (Criteria) this;
		}

		public Criteria andK0027NotBetween(String value1, String value2) {
			addCriterion("K0027 not between", value1, value2, "k0027");
			return (Criteria) this;
		}

		public Criteria andK0028IsNull() {
			addCriterion("K0028 is null");
			return (Criteria) this;
		}

		public Criteria andK0028IsNotNull() {
			addCriterion("K0028 is not null");
			return (Criteria) this;
		}

		public Criteria andK0028EqualTo(String value) {
			addCriterion("K0028 =", value, "k0028");
			return (Criteria) this;
		}

		public Criteria andK0028NotEqualTo(String value) {
			addCriterion("K0028 <>", value, "k0028");
			return (Criteria) this;
		}

		public Criteria andK0028GreaterThan(String value) {
			addCriterion("K0028 >", value, "k0028");
			return (Criteria) this;
		}

		public Criteria andK0028GreaterThanOrEqualTo(String value) {
			addCriterion("K0028 >=", value, "k0028");
			return (Criteria) this;
		}

		public Criteria andK0028LessThan(String value) {
			addCriterion("K0028 <", value, "k0028");
			return (Criteria) this;
		}

		public Criteria andK0028LessThanOrEqualTo(String value) {
			addCriterion("K0028 <=", value, "k0028");
			return (Criteria) this;
		}

		public Criteria andK0028Like(String value) {
			addCriterion("K0028 like", value, "k0028");
			return (Criteria) this;
		}

		public Criteria andK0028NotLike(String value) {
			addCriterion("K0028 not like", value, "k0028");
			return (Criteria) this;
		}

		public Criteria andK0028In(List<String> values) {
			addCriterion("K0028 in", values, "k0028");
			return (Criteria) this;
		}

		public Criteria andK0028NotIn(List<String> values) {
			addCriterion("K0028 not in", values, "k0028");
			return (Criteria) this;
		}

		public Criteria andK0028Between(String value1, String value2) {
			addCriterion("K0028 between", value1, value2, "k0028");
			return (Criteria) this;
		}

		public Criteria andK0028NotBetween(String value1, String value2) {
			addCriterion("K0028 not between", value1, value2, "k0028");
			return (Criteria) this;
		}

		public Criteria andK0029IsNull() {
			addCriterion("K0029 is null");
			return (Criteria) this;
		}

		public Criteria andK0029IsNotNull() {
			addCriterion("K0029 is not null");
			return (Criteria) this;
		}

		public Criteria andK0029EqualTo(String value) {
			addCriterion("K0029 =", value, "k0029");
			return (Criteria) this;
		}

		public Criteria andK0029NotEqualTo(String value) {
			addCriterion("K0029 <>", value, "k0029");
			return (Criteria) this;
		}

		public Criteria andK0029GreaterThan(String value) {
			addCriterion("K0029 >", value, "k0029");
			return (Criteria) this;
		}

		public Criteria andK0029GreaterThanOrEqualTo(String value) {
			addCriterion("K0029 >=", value, "k0029");
			return (Criteria) this;
		}

		public Criteria andK0029LessThan(String value) {
			addCriterion("K0029 <", value, "k0029");
			return (Criteria) this;
		}

		public Criteria andK0029LessThanOrEqualTo(String value) {
			addCriterion("K0029 <=", value, "k0029");
			return (Criteria) this;
		}

		public Criteria andK0029Like(String value) {
			addCriterion("K0029 like", value, "k0029");
			return (Criteria) this;
		}

		public Criteria andK0029NotLike(String value) {
			addCriterion("K0029 not like", value, "k0029");
			return (Criteria) this;
		}

		public Criteria andK0029In(List<String> values) {
			addCriterion("K0029 in", values, "k0029");
			return (Criteria) this;
		}

		public Criteria andK0029NotIn(List<String> values) {
			addCriterion("K0029 not in", values, "k0029");
			return (Criteria) this;
		}

		public Criteria andK0029Between(String value1, String value2) {
			addCriterion("K0029 between", value1, value2, "k0029");
			return (Criteria) this;
		}

		public Criteria andK0029NotBetween(String value1, String value2) {
			addCriterion("K0029 not between", value1, value2, "k0029");
			return (Criteria) this;
		}

		public Criteria andGenesIsNull() {
			addCriterion("genes is null");
			return (Criteria) this;
		}

		public Criteria andGenesIsNotNull() {
			addCriterion("genes is not null");
			return (Criteria) this;
		}

		public Criteria andGenesEqualTo(String value) {
			addCriterion("genes =", value, "genes");
			return (Criteria) this;
		}

		public Criteria andGenesNotEqualTo(String value) {
			addCriterion("genes <>", value, "genes");
			return (Criteria) this;
		}

		public Criteria andGenesGreaterThan(String value) {
			addCriterion("genes >", value, "genes");
			return (Criteria) this;
		}

		public Criteria andGenesGreaterThanOrEqualTo(String value) {
			addCriterion("genes >=", value, "genes");
			return (Criteria) this;
		}

		public Criteria andGenesLessThan(String value) {
			addCriterion("genes <", value, "genes");
			return (Criteria) this;
		}

		public Criteria andGenesLessThanOrEqualTo(String value) {
			addCriterion("genes <=", value, "genes");
			return (Criteria) this;
		}

		public Criteria andGenesLike(String value) {
			addCriterion("genes like", value, "genes");
			return (Criteria) this;
		}

		public Criteria andGenesNotLike(String value) {
			addCriterion("genes not like", value, "genes");
			return (Criteria) this;
		}

		public Criteria andGenesIn(List<String> values) {
			addCriterion("genes in", values, "genes");
			return (Criteria) this;
		}

		public Criteria andGenesNotIn(List<String> values) {
			addCriterion("genes not in", values, "genes");
			return (Criteria) this;
		}

		public Criteria andGenesBetween(String value1, String value2) {
			addCriterion("genes between", value1, value2, "genes");
			return (Criteria) this;
		}

		public Criteria andGenesNotBetween(String value1, String value2) {
			addCriterion("genes not between", value1, value2, "genes");
			return (Criteria) this;
		}

		public Criteria andTagsIsNull() {
			addCriterion("tags is null");
			return (Criteria) this;
		}

		public Criteria andTagsIsNotNull() {
			addCriterion("tags is not null");
			return (Criteria) this;
		}

		public Criteria andTagsEqualTo(String value) {
			addCriterion("tags =", value, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsNotEqualTo(String value) {
			addCriterion("tags <>", value, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsGreaterThan(String value) {
			addCriterion("tags >", value, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsGreaterThanOrEqualTo(String value) {
			addCriterion("tags >=", value, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsLessThan(String value) {
			addCriterion("tags <", value, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsLessThanOrEqualTo(String value) {
			addCriterion("tags <=", value, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsLike(String value) {
			addCriterion("tags like", value, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsNotLike(String value) {
			addCriterion("tags not like", value, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsIn(List<String> values) {
			addCriterion("tags in", values, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsNotIn(List<String> values) {
			addCriterion("tags not in", values, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsBetween(String value1, String value2) {
			addCriterion("tags between", value1, value2, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsNotBetween(String value1, String value2) {
			addCriterion("tags not between", value1, value2, "tags");
			return (Criteria) this;
		}

		public Criteria andFprimerIsNull() {
			addCriterion("fprimer is null");
			return (Criteria) this;
		}

		public Criteria andFprimerIsNotNull() {
			addCriterion("fprimer is not null");
			return (Criteria) this;
		}

		public Criteria andFprimerEqualTo(String value) {
			addCriterion("fprimer =", value, "fprimer");
			return (Criteria) this;
		}

		public Criteria andFprimerNotEqualTo(String value) {
			addCriterion("fprimer <>", value, "fprimer");
			return (Criteria) this;
		}

		public Criteria andFprimerGreaterThan(String value) {
			addCriterion("fprimer >", value, "fprimer");
			return (Criteria) this;
		}

		public Criteria andFprimerGreaterThanOrEqualTo(String value) {
			addCriterion("fprimer >=", value, "fprimer");
			return (Criteria) this;
		}

		public Criteria andFprimerLessThan(String value) {
			addCriterion("fprimer <", value, "fprimer");
			return (Criteria) this;
		}

		public Criteria andFprimerLessThanOrEqualTo(String value) {
			addCriterion("fprimer <=", value, "fprimer");
			return (Criteria) this;
		}

		public Criteria andFprimerLike(String value) {
			addCriterion("fprimer like", value, "fprimer");
			return (Criteria) this;
		}

		public Criteria andFprimerNotLike(String value) {
			addCriterion("fprimer not like", value, "fprimer");
			return (Criteria) this;
		}

		public Criteria andFprimerIn(List<String> values) {
			addCriterion("fprimer in", values, "fprimer");
			return (Criteria) this;
		}

		public Criteria andFprimerNotIn(List<String> values) {
			addCriterion("fprimer not in", values, "fprimer");
			return (Criteria) this;
		}

		public Criteria andFprimerBetween(String value1, String value2) {
			addCriterion("fprimer between", value1, value2, "fprimer");
			return (Criteria) this;
		}

		public Criteria andFprimerNotBetween(String value1, String value2) {
			addCriterion("fprimer not between", value1, value2, "fprimer");
			return (Criteria) this;
		}

		public Criteria andRprimerIsNull() {
			addCriterion("rprimer is null");
			return (Criteria) this;
		}

		public Criteria andRprimerIsNotNull() {
			addCriterion("rprimer is not null");
			return (Criteria) this;
		}

		public Criteria andRprimerEqualTo(String value) {
			addCriterion("rprimer =", value, "rprimer");
			return (Criteria) this;
		}

		public Criteria andRprimerNotEqualTo(String value) {
			addCriterion("rprimer <>", value, "rprimer");
			return (Criteria) this;
		}

		public Criteria andRprimerGreaterThan(String value) {
			addCriterion("rprimer >", value, "rprimer");
			return (Criteria) this;
		}

		public Criteria andRprimerGreaterThanOrEqualTo(String value) {
			addCriterion("rprimer >=", value, "rprimer");
			return (Criteria) this;
		}

		public Criteria andRprimerLessThan(String value) {
			addCriterion("rprimer <", value, "rprimer");
			return (Criteria) this;
		}

		public Criteria andRprimerLessThanOrEqualTo(String value) {
			addCriterion("rprimer <=", value, "rprimer");
			return (Criteria) this;
		}

		public Criteria andRprimerLike(String value) {
			addCriterion("rprimer like", value, "rprimer");
			return (Criteria) this;
		}

		public Criteria andRprimerNotLike(String value) {
			addCriterion("rprimer not like", value, "rprimer");
			return (Criteria) this;
		}

		public Criteria andRprimerIn(List<String> values) {
			addCriterion("rprimer in", values, "rprimer");
			return (Criteria) this;
		}

		public Criteria andRprimerNotIn(List<String> values) {
			addCriterion("rprimer not in", values, "rprimer");
			return (Criteria) this;
		}

		public Criteria andRprimerBetween(String value1, String value2) {
			addCriterion("rprimer between", value1, value2, "rprimer");
			return (Criteria) this;
		}

		public Criteria andRprimerNotBetween(String value1, String value2) {
			addCriterion("rprimer not between", value1, value2, "rprimer");
			return (Criteria) this;
		}

		public Criteria andLtmIsNull() {
			addCriterion("ltm is null");
			return (Criteria) this;
		}

		public Criteria andLtmIsNotNull() {
			addCriterion("ltm is not null");
			return (Criteria) this;
		}

		public Criteria andLtmEqualTo(Float value) {
			addCriterion("ltm =", value, "ltm");
			return (Criteria) this;
		}

		public Criteria andLtmNotEqualTo(Float value) {
			addCriterion("ltm <>", value, "ltm");
			return (Criteria) this;
		}

		public Criteria andLtmGreaterThan(Float value) {
			addCriterion("ltm >", value, "ltm");
			return (Criteria) this;
		}

		public Criteria andLtmGreaterThanOrEqualTo(Float value) {
			addCriterion("ltm >=", value, "ltm");
			return (Criteria) this;
		}

		public Criteria andLtmLessThan(Float value) {
			addCriterion("ltm <", value, "ltm");
			return (Criteria) this;
		}

		public Criteria andLtmLessThanOrEqualTo(Float value) {
			addCriterion("ltm <=", value, "ltm");
			return (Criteria) this;
		}

		public Criteria andLtmIn(List<Float> values) {
			addCriterion("ltm in", values, "ltm");
			return (Criteria) this;
		}

		public Criteria andLtmNotIn(List<Float> values) {
			addCriterion("ltm not in", values, "ltm");
			return (Criteria) this;
		}

		public Criteria andLtmBetween(Float value1, Float value2) {
			addCriterion("ltm between", value1, value2, "ltm");
			return (Criteria) this;
		}

		public Criteria andLtmNotBetween(Float value1, Float value2) {
			addCriterion("ltm not between", value1, value2, "ltm");
			return (Criteria) this;
		}

		public Criteria andRtmIsNull() {
			addCriterion("rtm is null");
			return (Criteria) this;
		}

		public Criteria andRtmIsNotNull() {
			addCriterion("rtm is not null");
			return (Criteria) this;
		}

		public Criteria andRtmEqualTo(Float value) {
			addCriterion("rtm =", value, "rtm");
			return (Criteria) this;
		}

		public Criteria andRtmNotEqualTo(Float value) {
			addCriterion("rtm <>", value, "rtm");
			return (Criteria) this;
		}

		public Criteria andRtmGreaterThan(Float value) {
			addCriterion("rtm >", value, "rtm");
			return (Criteria) this;
		}

		public Criteria andRtmGreaterThanOrEqualTo(Float value) {
			addCriterion("rtm >=", value, "rtm");
			return (Criteria) this;
		}

		public Criteria andRtmLessThan(Float value) {
			addCriterion("rtm <", value, "rtm");
			return (Criteria) this;
		}

		public Criteria andRtmLessThanOrEqualTo(Float value) {
			addCriterion("rtm <=", value, "rtm");
			return (Criteria) this;
		}

		public Criteria andRtmIn(List<Float> values) {
			addCriterion("rtm in", values, "rtm");
			return (Criteria) this;
		}

		public Criteria andRtmNotIn(List<Float> values) {
			addCriterion("rtm not in", values, "rtm");
			return (Criteria) this;
		}

		public Criteria andRtmBetween(Float value1, Float value2) {
			addCriterion("rtm between", value1, value2, "rtm");
			return (Criteria) this;
		}

		public Criteria andRtmNotBetween(Float value1, Float value2) {
			addCriterion("rtm not between", value1, value2, "rtm");
			return (Criteria) this;
		}

		public Criteria andPsizeIsNull() {
			addCriterion("psize is null");
			return (Criteria) this;
		}

		public Criteria andPsizeIsNotNull() {
			addCriterion("psize is not null");
			return (Criteria) this;
		}

		public Criteria andPsizeEqualTo(Integer value) {
			addCriterion("psize =", value, "psize");
			return (Criteria) this;
		}

		public Criteria andPsizeNotEqualTo(Integer value) {
			addCriterion("psize <>", value, "psize");
			return (Criteria) this;
		}

		public Criteria andPsizeGreaterThan(Integer value) {
			addCriterion("psize >", value, "psize");
			return (Criteria) this;
		}

		public Criteria andPsizeGreaterThanOrEqualTo(Integer value) {
			addCriterion("psize >=", value, "psize");
			return (Criteria) this;
		}

		public Criteria andPsizeLessThan(Integer value) {
			addCriterion("psize <", value, "psize");
			return (Criteria) this;
		}

		public Criteria andPsizeLessThanOrEqualTo(Integer value) {
			addCriterion("psize <=", value, "psize");
			return (Criteria) this;
		}

		public Criteria andPsizeIn(List<Integer> values) {
			addCriterion("psize in", values, "psize");
			return (Criteria) this;
		}

		public Criteria andPsizeNotIn(List<Integer> values) {
			addCriterion("psize not in", values, "psize");
			return (Criteria) this;
		}

		public Criteria andPsizeBetween(Integer value1, Integer value2) {
			addCriterion("psize between", value1, value2, "psize");
			return (Criteria) this;
		}

		public Criteria andPsizeNotBetween(Integer value1, Integer value2) {
			addCriterion("psize not between", value1, value2, "psize");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table SNP_Marker
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table snp_marker
     *
     * @mbggenerated do_not_delete_during_merge Sat Feb 01 21:45:13 KST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}