package kr.re.kribb.model;

public class Trait {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trait.code
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trait.commonName
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String commonname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trait.trait
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	private String trait;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trait.code
	 * @return  the value of trait.code
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trait.code
	 * @param code  the value for trait.code
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trait.commonName
	 * @return  the value of trait.commonName
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getCommonname() {
		return commonname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trait.commonName
	 * @param commonname  the value for trait.commonName
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setCommonname(String commonname) {
		this.commonname = commonname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trait.trait
	 * @return  the value of trait.trait
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public String getTrait() {
		return trait;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trait.trait
	 * @param trait  the value for trait.trait
	 * @mbggenerated  Wed Jul 30 09:22:09 KST 2014
	 */
	public void setTrait(String trait) {
		this.trait = trait;
	}
}